/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--bg-primary, #FFFFFF)',
        'bg-secondary': 'var(--bg-secondary, #F5F5F5)',
        'bg-tertiary': 'var(--bg-tertiary, #EDEDED)',
        'bg-hover': 'var(--bg-hover, #E5E5E5)',
        'text-primary': 'var(--text-primary, #000000)',
        'text-secondary': 'var(--text-secondary, #333333)',
        'text-muted': 'var(--text-muted, #666666)',
        'accent': 'var(--accent, #C108AB)',
        'accent-light': 'var(--accent-light, #E040C8)',
        /* Brand palette */
        'teal': 'var(--teal, #00897B)',
        'teal-light': 'var(--teal-light, #4DB6AC)',
        'ocean': 'var(--ocean, #4FC3F7)',
        'ocean-deep': 'var(--ocean-deep, #0288D1)',
        'slate': 'var(--slate, #607D8B)',
        'sky': 'var(--sky, #E8F4FD)',
        'mist': 'var(--mist, #F0F7FF)',
        'lavender': 'var(--lavender, #EDE7F6)',
        'cream': 'var(--cream, #FAFAFA)',
        /* Fuchsia opacity scale */
        'accent-5': 'var(--accent-5, #c108ab08)',
        'accent-10': 'var(--accent-10, #c108ab1a)',
        'accent-15': 'var(--accent-15, #c108ab26)',
        'accent-20': 'var(--accent-20, #c108ab33)',
        /* Pipeline tier colors — semantic only */
        'tier-1': '#16A34A',
        'tier-1Bg': 'rgba(22,163,74,0.15)',
        'tier-2': '#CA8A04',
        'tier-2Bg': 'rgba(202,138,4,0.15)',
        'tier-3': '#6B7280',
        'tier-3Bg': 'rgba(107,114,128,0.15)',
        /* SWEEP stage — teal replaces indigo */
        'sweep': 'var(--teal, #00897B)',
        'sweep-light': 'var(--teal-light, #4DB6AC)',
      },
      fontFamily: {
        serif: ['Libre Baskerville', 'Georgia', 'serif'],
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
      },
      animation: {
        'pulse-icon': 'iconPulse 2s ease-in-out infinite',
        'rotate-icon': 'iconRotate 8s linear infinite',
        'draw-icon': 'iconDraw 3s ease-in-out infinite',
        'glow-cta': 'ctaGlow 2.5s ease-in-out infinite',
        'float': 'dreamyFloat 8s ease-in-out infinite',
        'enter': 'pageEnter 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'bridge': 'iconBridgeConnect 3s ease-in-out infinite',
        'coach': 'iconCoachBlow 2.5s ease-in-out infinite',
        'drive': 'iconDriveThrust 2s ease-in-out infinite',
        'forge': 'iconForgeStrike 2s ease-in-out infinite',
        'impact': 'iconImpactRipple 1.8s ease-out infinite',
        'leap': 'iconLeapRise 2s ease-in-out infinite',
        'mosaic': 'iconMosaicShift 4s ease-in-out infinite',
        'prism': 'iconPrismShimmer 3s ease-in-out infinite',
        'quest': 'iconQuestSpin 6s linear infinite',
        'spark': 'iconSparkFlash 2s ease-in-out infinite',
        'trident': 'iconTridentPulse 2s ease-in-out infinite',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};