// Phase 0.7: KPI Registry
// All KPI definitions with formulas, thresholds, and metadata

import type { KpiDefinition } from '@/types/kpis';

export const KPI_REGISTRY: KpiDefinition[] = [
  // =========================================================================
  // Revenue & Business KPIs
  // =========================================================================
  {
    id: 'mrr',
    name: 'Monthly Recurring Revenue',
    category: 'revenue',
    description: 'Total active subscription revenue per month',
    formula: 'SUM(active_subscriptions × plan_price)',
    unit: 'currency',
    frequency: 'daily',
    data_source: ['subscriptions', 'plans'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 2,
  },
  {
    id: 'acv',
    name: 'Annual Contract Value',
    category: 'revenue',
    description: 'Average annual value per client contract',
    formula: 'MRR × 12',
    unit: 'currency',
    frequency: 'monthly',
    data_source: ['subscriptions', 'plans'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 2,
  },
  {
    id: 'clv',
    name: 'Customer Lifetime Value',
    category: 'revenue',
    description: 'Predicted total revenue from average customer over lifetime',
    formula: 'ACV × avg_retention_months',
    unit: 'currency',
    frequency: 'monthly',
    data_source: ['subscriptions', 'churn_events'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 2,
  },
  {
    id: 'cac',
    name: 'Customer Acquisition Cost',
    category: 'revenue',
    description: 'Average cost to acquire a new client',
    formula: 'total_sales_cost / new_clients_this_period',
    unit: 'currency',
    frequency: 'monthly',
    data_source: ['clients'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: false,
    precision: 2,
  },
  {
    id: 'ltv_cac_ratio',
    name: 'LTV:CAC Ratio',
    category: 'revenue',
    description: 'Ratio of customer lifetime value to acquisition cost',
    formula: 'CLV / CAC',
    unit: 'ratio',
    frequency: 'quarterly',
    target: 3,
    warning_threshold: 2,
    critical_threshold: 1,
    data_source: ['subscriptions', 'clients'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 1,
  },
  {
    id: 'nrr',
    name: 'Net Revenue Retention',
    category: 'revenue',
    description: 'Revenue retained from existing customers including expansion',
    formula: '(starting_MRR + expansion - contraction - churn) / starting_MRR',
    unit: 'percentage',
    frequency: 'monthly',
    target: 110,
    warning_threshold: 100,
    critical_threshold: 90,
    data_source: ['subscriptions', 'subscription_events'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 1,
  },

  // =========================================================================
  // Recruitment Efficiency KPIs
  // =========================================================================
  {
    id: 'time_to_shortlist',
    name: 'Time to Shortlist',
    category: 'recruitment_efficiency',
    description: 'Average days from mandate creation to first shortlist',
    formula: 'AVG(shortlist.created_at − mandate.created_at)',
    unit: 'days',
    frequency: 'weekly',
    target: 7,
    warning_threshold: 14,
    critical_threshold: 21,
    data_source: ['mandates', 'shortlists'],
    dashboard: ['client_portal', 'b2b_dashboard'],
    higher_is_better: false,
    precision: 1,
  },
  {
    id: 'time_to_hire',
    name: 'Time to Hire',
    category: 'recruitment_efficiency',
    description: 'Average days from mandate creation to accepted offer',
    formula: 'AVG(placement.accepted_at − mandate.created_at)',
    unit: 'days',
    frequency: 'weekly',
    target: 30,
    warning_threshold: 45,
    critical_threshold: 60,
    data_source: ['mandates', 'placements'],
    dashboard: ['client_portal', 'b2b_dashboard'],
    higher_is_better: false,
    precision: 1,
  },
  {
    id: 'shortlist_to_interview_ratio',
    name: 'Shortlist-to-Interview Ratio',
    category: 'recruitment_efficiency',
    description: 'Percentage of shortlisted candidates who get interviews',
    formula: 'interviews_scheduled / candidates_shortlisted × 100',
    unit: 'percentage',
    frequency: 'weekly',
    target: 60,
    warning_threshold: 40,
    critical_threshold: 20,
    data_source: ['shortlists', 'interviews'],
    dashboard: ['client_portal'],
    higher_is_better: true,
    precision: 1,
  },
  {
    id: 'interview_to_offer_ratio',
    name: 'Interview-to-Offer Ratio',
    category: 'recruitment_efficiency',
    description: 'Percentage of completed interviews that result in offers',
    formula: 'offers_made / interviews_completed × 100',
    unit: 'percentage',
    frequency: 'weekly',
    target: 30,
    warning_threshold: 20,
    critical_threshold: 10,
    data_source: ['interviews', 'offers'],
    dashboard: ['client_portal'],
    higher_is_better: true,
    precision: 1,
  },
  {
    id: 'offer_acceptance_rate',
    name: 'Offer Acceptance Rate',
    category: 'recruitment_efficiency',
    description: 'Percentage of offers accepted vs. made',
    formula: 'offers_accepted / offers_made × 100',
    unit: 'percentage',
    frequency: 'monthly',
    target: 80,
    warning_threshold: 60,
    critical_threshold: 40,
    data_source: ['offers'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 1,
  },
  {
    id: 'pipeline_velocity',
    name: 'Pipeline Velocity',
    category: 'recruitment_efficiency',
    description: 'Average candidates moved forward per week',
    formula: 'candidates_moved_forward / total_in_pipeline / weeks',
    unit: 'ratio',
    frequency: 'weekly',
    data_source: ['shift_stages', 'candidates'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 2,
  },
  {
    id: 'mandate_fill_rate',
    name: 'Mandate Fill Rate',
    category: 'recruitment_efficiency',
    description: 'Percentage of mandates successfully filled',
    formula: 'filled_mandates / total_active_mandates × 100',
    unit: 'percentage',
    frequency: 'monthly',
    target: 75,
    warning_threshold: 50,
    critical_threshold: 30,
    data_source: ['mandates'],
    dashboard: ['b2b_dashboard', 'client_portal'],
    higher_is_better: true,
    precision: 1,
  },

  // =========================================================================
  // Candidate Experience KPIs
  // =========================================================================
  {
    id: 'candidate_engagement_rate',
    name: 'Candidate Engagement Rate',
    category: 'candidate_experience',
    description: 'Percentage of candidates active in last 7 days',
    formula: 'active_candidates_7d / total_candidates × 100',
    unit: 'percentage',
    frequency: 'weekly',
    target: 60,
    warning_threshold: 40,
    critical_threshold: 20,
    data_source: ['candidates', 'login_events'],
    dashboard: ['candidate_portal'],
    higher_is_better: true,
    precision: 1,
  },
  {
    id: 'application_completion_rate',
    name: 'Application Completion Rate',
    category: 'candidate_experience',
    description: 'Percentage of started applications that are completed',
    formula: 'completed_applications / started_applications × 100',
    unit: 'percentage',
    frequency: 'weekly',
    target: 75,
    warning_threshold: 50,
    critical_threshold: 30,
    data_source: ['applications'],
    dashboard: ['candidate_portal'],
    higher_is_better: true,
    precision: 1,
  },
  {
    id: 'assessment_completion_rate',
    name: 'Assessment Completion Rate',
    category: 'candidate_experience',
    description: 'Percentage of assigned assessments completed',
    formula: 'completed_assessments / assigned_assessments × 100',
    unit: 'percentage',
    frequency: 'weekly',
    target: 85,
    warning_threshold: 60,
    critical_threshold: 40,
    data_source: ['assessments'],
    dashboard: ['candidate_portal'],
    higher_is_better: true,
    precision: 1,
  },
  {
    id: 'candidate_nps',
    name: 'Candidate Net Promoter Score',
    category: 'candidate_experience',
    description: 'NPS from candidate satisfaction surveys',
    formula: '(promoters − detractors) / total_respondents × 100',
    unit: 'score',
    frequency: 'monthly',
    target: 40,
    warning_threshold: 20,
    critical_threshold: 0,
    data_source: ['feedback_surveys'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 0,
  },
  {
    id: 'withdrawal_rate',
    name: 'Withdrawal Rate',
    category: 'candidate_experience',
    description: 'Percentage of candidates who withdraw from pipeline',
    formula: 'withdrawn_candidates / total_in_pipeline × 100',
    unit: 'percentage',
    frequency: 'weekly',
    target: 15,
    warning_threshold: 25,
    critical_threshold: 40,
    data_source: ['candidates', 'pipeline_events'],
    dashboard: ['internal'],
    higher_is_better: false,
    precision: 1,
  },
  {
    id: 'time_in_stage',
    name: 'Time in Stage',
    category: 'candidate_experience',
    description: 'Average time candidates spend in each pipeline stage',
    formula: 'AVG(now() − stage_entered_at) per stage per mandate',
    unit: 'days',
    frequency: 'realtime',
    data_source: ['shift_stages'],
    dashboard: ['client_portal'],
    higher_is_better: false,
    precision: 1,
  },

  // =========================================================================
  // Consultant Performance KPIs
  // =========================================================================
  {
    id: 'consultant_utilization',
    name: 'Consultant Utilization',
    category: 'consultant_performance',
    description: 'Billable hours as percentage of available hours',
    formula: 'billable_hours / total_available_hours × 100',
    unit: 'percentage',
    frequency: 'monthly',
    target: 75,
    warning_threshold: 50,
    critical_threshold: 30,
    data_source: ['time_entries', 'contracts'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 1,
  },
  {
    id: 'candidates_per_consultant',
    name: 'Candidates per Consultant',
    category: 'consultant_performance',
    description: 'Average number of candidates managed per consultant',
    formula: 'candidates_managed / active_consultants',
    unit: 'count',
    frequency: 'monthly',
    target: 50,
    warning_threshold: 30,
    critical_threshold: 15,
    data_source: ['candidates', 'consultants'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 0,
  },
  {
    id: 'placement_rate_per_consultant',
    name: 'Placement Rate per Consultant',
    category: 'consultant_performance',
    description: 'Placements made per consultant per month',
    formula: 'placements_made / active_consultants',
    unit: 'count',
    frequency: 'monthly',
    target: 3,
    warning_threshold: 2,
    critical_threshold: 1,
    data_source: ['placements', 'consultants'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 1,
  },
  {
    id: 'revenue_per_consultant',
    name: 'Revenue per Consultant',
    category: 'consultant_performance',
    description: 'Revenue generated from placements per consultant',
    formula: 'revenue_from_placements / active_consultants',
    unit: 'currency',
    frequency: 'monthly',
    data_source: ['placements', 'invoices'],
    dashboard: ['b2b_dashboard'],
    higher_is_better: true,
    precision: 2,
  },
  {
    id: 'consultant_nps',
    name: 'Consultant NPS',
    category: 'consultant_performance',
    description: 'NPS from consultant satisfaction surveys',
    formula: '(promoters − detractors) / total_respondents × 100',
    unit: 'score',
    frequency: 'quarterly',
    target: 50,
    warning_threshold: 30,
    critical_threshold: 10,
    data_source: ['consultant_surveys'],
    dashboard: ['internal'],
    higher_is_better: true,
    precision: 0,
  },

  // =========================================================================
  // Platform Health KPIs
  // =========================================================================
  {
    id: 'system_uptime',
    name: 'System Uptime',
    category: 'platform_health',
    description: 'Percentage of time the platform is operational',
    formula: 'uptime_minutes / total_minutes × 100',
    unit: 'percentage',
    frequency: 'realtime',
    target: 99.9,
    warning_threshold: 99.5,
    critical_threshold: 99,
    data_source: ['health_checks'],
    dashboard: ['internal'],
    higher_is_better: true,
    precision: 2,
  },
  {
    id: 'api_latency_p95',
    name: 'API Latency (P95)',
    category: 'platform_health',
    description: '95th percentile API response time',
    formula: '95th percentile response time',
    unit: 'minutes',
    frequency: 'realtime',
    target: 500,
    warning_threshold: 1000,
    critical_threshold: 2000,
    data_source: ['analytics'],
    dashboard: ['internal'],
    higher_is_better: false,
    precision: 0,
  },
  {
    id: 'error_rate',
    name: 'Error Rate',
    category: 'platform_health',
    description: 'Percentage of API responses that are errors',
    formula: 'error_responses / total_responses × 100',
    unit: 'percentage',
    frequency: 'realtime',
    target: 0.5,
    warning_threshold: 1,
    critical_threshold: 5,
    data_source: ['logs'],
    dashboard: ['internal'],
    higher_is_better: false,
    precision: 2,
  },
  {
    id: 'data_freshness',
    name: 'Data Freshness',
    category: 'platform_health',
    description: 'Age of most recent data sync',
    formula: 'now() − last_sync_timestamp',
    unit: 'hours',
    frequency: 'realtime',
    target: 1,
    warning_threshold: 6,
    critical_threshold: 24,
    data_source: ['sync_log'],
    dashboard: ['internal'],
    higher_is_better: false,
    precision: 1,
  },
];

export const KPIS_BY_CATEGORY = KPI_REGISTRY.reduce<Record<string, KpiDefinition[]>>(
  (acc, kpi) => {
    if (!acc[kpi.category]) {
      acc[kpi.category] = [];
    }
    acc[kpi.category].push(kpi);
    return acc;
  },
  {}
);

export const KPI_MAP = KPI_REGISTRY.reduce<Record<string, KpiDefinition>>(
  (acc, kpi) => {
    acc[kpi.id] = kpi;
    return acc;
  },
  {}
);

export function getKpiById(id: string): KpiDefinition | undefined {
  return KPI_MAP[id];
}

export function getKpisByDashboard(dashboard: string): KpiDefinition[] {
  return KPI_REGISTRY.filter(kpi => kpi.dashboard.includes(dashboard as KpiDefinition['dashboard'][number]));
}

export default KPI_REGISTRY;
