/**
 * LegalPages — Terms of Service, Privacy Policy, Cookie Policy (S4-T03)
 *
 * Public legal compliance pages required before production launch.
 * Content covers the key sections specified in the Legal Pages spec,
 * including GDPR + PIPL user rights, third-party processors
 * (DeepSeek, Supabase, Stripe), and PRC/Shanghai governing law.
 */
import React, { useState } from 'react';
import { ArrowLeft, FileText, Shield, Cookie, Download, Trash2, Loader2, AlertCircle, CheckCircle2 } from 'lucide-react';
import { useAuthStore } from '@/stores/authStore';
import { authFetch } from '@/utils/authFetch';

interface Section {
  heading: string;
  body: React.ReactNode;
}

function LegalLayout({ title, icon, intro, sections, lastUpdated, actions }: {
  title: string;
  icon: React.ReactNode;
  intro: string;
  sections: Section[];
  lastUpdated: string;
  actions?: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 md:px-6 py-12">
        <a href="/" className="flex items-center gap-1 text-sm text-gray-500 hover:text-fuchsia mb-8">
          <ArrowLeft className="w-4 h-4" /> Back to home
        </a>
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 bg-fuchsia/10 text-fuchsia flex items-center justify-center">{icon}</div>
          <h1
            className="text-3xl font-bold text-[#1A1A2E]"
            style={{ fontFamily: "'Libre Baskerville', Georgia, serif" }}
          >
            {title}
          </h1>
        </div>
        <p className="text-xs text-gray-400 mb-6">Last updated: {lastUpdated}</p>
        <p className="text-sm text-gray-600 leading-relaxed mb-8">{intro}</p>
        <div className="space-y-8">
          {sections.map((s, i) => (
            <section key={i}>
              <h2 className="font-semibold text-[#1A1A2E] mb-2">{i + 1}. {s.heading}</h2>
              <div className="text-sm text-gray-700 leading-relaxed space-y-2">{s.body}</div>
            </section>
          ))}
        </div>
        {actions}
        <div className="mt-12 pt-6 border-t border-gray-100 text-xs text-gray-400">
          LYC Partners Shanghai · For questions about this policy, contact{''}
          <a href="mailto:legal@lyc-intelligence.app" className="text-fuchsia hover:underline">legal@lyc-intelligence.app</a>
        </div>
      </div>
    </div>
  );
}

// ── Terms of Service ──
export function TermsPage() {
  const sections: Section[] = [
    {
      heading: 'Service Description',
      body: <p>LYC Intelligence ("the Service") is an executive intelligence platform operated by LYC Partners Shanghai, providing AI-powered advisory (DEX AI), candidate-client matching, assessment tools, and coaching services for China-APAC executives and the organizations that hire them.</p>,
    },
    {
      heading: 'User Accounts',
      body: <p>You must provide accurate information when creating an account and are responsible for safeguarding your credentials. We reserve the right to suspend accounts that violate these terms or applicable law.</p>,
    },
    {
      heading: 'Miles & Payment',
      body: <p>The Service uses a miles-based system. Your "Executive Introduction" provides 5 complimentary messages. Additional miles may be purchased. Miles are non-refundable except where required by law and do not expire unless stated otherwise at purchase. Council memberships are billed as subscriptions and may be cancelled per their terms.</p>,
    },
    {
      heading: 'AI Disclaimer',
      body: <p>DEX AI responses are generated by language models and constitute advisory guidance only. They are not legal, financial, or investment advice. You should consult qualified professionals before making decisions based on AI output. We do not guarantee the accuracy or completeness of AI-generated content.</p>,
    },
    {
      heading: 'Intellectual Property',
      body: <p>All platform content, software, and branding are the property of LYC Partners or its licensors. You retain rights to content you submit (e.g., assessment answers, resumes) and grant us a license to process it solely to provide the Service.</p>,
    },
    {
      heading: 'Acceptable Use',
      body: <p>You agree not to misuse the Service, including reverse-engineering, scraping data, transmitting malware, or using the Service for unlawful purposes. Candidate and client data must be handled in compliance with applicable privacy laws.</p>,
    },
    {
      heading: 'Limitation of Liability',
      body: <p>To the maximum extent permitted by law, LYC Partners' total liability for any claim arising from the Service is limited to the amount you paid in the preceding 12 months, or the miles purchased, whichever is greater. We are not liable for indirect or consequential damages.</p>,
    },
    {
      heading: 'Governing Law & Dispute Resolution',
      body: <p>These terms are governed by the laws of the People's Republic of China (PRC). Any dispute shall first be resolved through good-faith negotiation. If unresolved within 30 days, the dispute shall be submitted to the Shanghai International Economic and Trade Arbitration Commission (SHIAC) for arbitration in Shanghai in accordance with its rules.</p>,
    },
    {
      heading: 'Changes',
      body: <p>We may update these terms. Material changes will be notified via email or in-app notice. Continued use after the effective date constitutes acceptance.</p>,
    },
  ];
  return (
    <LegalLayout
      title="Terms of Service"
      icon={<FileText className="w-5 h-5" />}
      intro="These Terms govern your use of LYC Intelligence. By accessing or using the Service, you agree to be bound by these Terms."
      sections={sections}
      lastUpdated="August 4, 2026"
    />
  );
}

// ── Privacy Policy ──
export function PrivacyPage() {
  const sections: Section[] = [
    {
      heading: 'Data Controller',
      body: <p>LYC Partners Shanghai is the data controller responsible for your personal data. Contact us at <a href="mailto:privacy@lyc-intelligence.app" className="text-fuchsia hover:underline">privacy@lyc-intelligence.app</a> for privacy inquiries.</p>,
    },
    {
      heading: 'Data We Collect',
      body: (
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Account data:</strong> name, email, password (hashed), role, organization.</li>
          <li><strong>Profile data:</strong> title, company, industry, seniority, location, resume.</li>
          <li><strong>Activity data:</strong> assessment answers, chat history, applications, bookings.</li>
          <li><strong>Usage data:</strong> device, browser, IP address, pages visited (via cookies).</li>
        </ul>
      ),
    },
    {
      heading: 'Purpose of Processing',
      body: <p>We process your data to provide the Service (matching, advisory, assessments), to operate and improve the platform, to communicate with you, to process payments, and to comply with legal obligations.</p>,
    },
    {
      heading: 'Third-Party Processors',
      body: (
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Supabase</strong> — database, authentication, and file storage (Netherlands).</li>
          <li><strong>DeepSeek</strong> — AI language model processing for DEX AI responses.</li>
          <li><strong>Stripe</strong> — payment processing (PCI-DSS compliant).</li>
          <li><strong>Vercel</strong> — application hosting and content delivery.</li>
        </ul>
      ),
    },
    {
      heading: 'Cross-Border Transfers',
      body: <p>Your data may be processed outside your country of residence, including in the EU, the United States, and the PRC. We rely on appropriate safeguards (e.g., standard contractual clauses) and comply with PRC Personal Information Protection Law (PIPL) cross-border transfer requirements where applicable.</p>,
    },
    {
      heading: 'Retention',
      body: <p>We retain personal data only as long as necessary for the purposes described or as required by law. Account data is retained while your account is active. You may request deletion; deletion is completed within 30 days, subject to legal retention obligations.</p>,
    },
    {
      heading: 'Your Rights (GDPR / PIPL)',
      body: (
        <ul className="list-disc pl-5 space-y-1">
          <li>Access, correct, or delete your personal data.</li>
          <li>Restrict or object to processing.</li>
          <li>Data portability (receive your data in a structured format).</li>
          <li>Withdraw consent at any time (without affecting prior processing).</li>
          <li>Lodge a complaint with your local data protection authority.</li>
        </ul>
      ),
    },
    {
      heading: 'Data Export & Deletion',
      body: <p>To exercise your rights, contact <a href="mailto:privacy@lyc-intelligence.app" className="text-fuchsia hover:underline">privacy@lyc-intelligence.app</a>. We will respond within 30 days. Account deletion initiates a soft delete followed by a hard delete after 30 days.</p>,
    },
    {
      heading: 'Security',
      body: <p>We use industry-standard measures including encryption in transit (TLS) and at rest, row-level security, and access controls. No method of transmission is 100% secure, but we work to protect your data.</p>,
    },
  ];
  return (
    <LegalLayout
      title="Privacy Policy"
      icon={<Shield className="w-5 h-5" />}
      intro="This Privacy Policy explains how LYC Partners Shanghai collects, uses, and protects your personal data when you use LYC Intelligence."
      sections={sections}
      lastUpdated="August 4, 2026"
      actions={<PrivacyActionsPanel />}
    />
  );
}

// ── Cookie Policy ──
export function CookiesPage() {
  const sections: Section[] = [
    {
      heading: 'What Are Cookies',
      body: <p>Cookies are small text files stored on your device when you visit a website. They help the site function and remember your preferences. We use two categories of cookies on LYC Intelligence.</p>,
    },
    {
      heading: 'Essential Cookies',
      body: <p>These are necessary for the Service to function. They enable authentication, session management, and security. Essential cookies cannot be disabled.</p>,
    },
    {
      heading: 'Analytics Cookies',
      body: <p>These help us understand how visitors use the site so we can improve it. They collect aggregated, anonymized usage data. Analytics cookies are only set after you consent via the cookie banner.</p>,
    },
    {
      heading: 'Consent',
      body: <p>On your first visit, a banner asks you to accept or reject non-essential cookies. Your choice is stored in your browser's local storage. You can change your choice at any time by clearing your browser storage or contacting us.</p>,
    },
    {
      heading: 'Managing Cookies',
      body: <p>You can also control cookies through your browser settings. Note that disabling essential cookies may prevent the Service from working correctly.</p>,
    },
    {
      heading: 'Third-Party Cookies',
      body: <p>Our third-party processors (Supabase, Stripe, Vercel) may set their own cookies as part of their services. These are governed by their respective privacy policies.</p>,
    },
  ];
  return (
    <LegalLayout
      title="Cookie Policy"
      icon={<Cookie className="w-5 h-5" />}
      intro="This policy explains how LYC Intelligence uses cookies and similar technologies, and how you can control them."
      sections={sections}
      lastUpdated="August 4, 2026"
    />
  );
}

export default LegalLayout;

// ── Self-service privacy actions (data export + account deletion) ──
function PrivacyActionsPanel() {
  const user = useAuthStore(s => s.user);
  const [exporting, setExporting] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [confirming, setConfirming] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const handleExport = async () => {
    setError(null);
    setSuccess(null);
    setExporting(true);
    try {
      const res = await authFetch('/api/user/data-export', { method: 'GET' });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `Request failed (${res.status})`);
      }
      const payload = await res.json();
      const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `lyc-personal-data-${new Date().toISOString().slice(0, 10)}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setSuccess('Your data export has been downloaded.');
    } catch (err: any) {
      setError(err?.message || 'Could not export your data right now.');
    } finally {
      setExporting(false);
    }
  };

  const handleDelete = async () => {
    setError(null);
    setSuccess(null);
    setDeleting(true);
    try {
      const res = await authFetch('/api/user/delete', { method: 'POST' });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body.error || `Request failed (${res.status})`);
      setSuccess(body.message || 'Account deletion scheduled. Personal data will be removed within 30 days.');
      setConfirming(false);
    } catch (err: any) {
      setError(err?.message || 'Could not complete deletion request.');
    } finally {
      setDeleting(false);
    }
  };

  // Not signed in — nudge to login rather than showing dead buttons.
  if (!user) {
    return (
      <div className="mt-12 p-5 border border-gray-200 bg-gray-50 text-sm text-gray-600 leading-relaxed">
        <div className="flex items-start gap-2">
          <AlertCircle className="w-4 h-4 text-gray-400 flex-shrink-0 mt-0.5" />
          <span>
            To download your personal data or request account deletion, please{''}
            <a href="/login" className="text-fuchsia hover:underline font-medium">sign in</a>{''}
            first. You may also email{''}
            <a href="mailto:privacy@lyc-intelligence.app" className="text-fuchsia hover:underline">privacy@lyc-intelligence.app</a>.
          </span>
        </div>
      </div>
    );
  }

  return (
    <div className="mt-12 p-5 border border-gray-200 bg-gray-50">
      <h3 className="font-semibold text-[#1A1A2E] mb-1">Exercise your rights</h3>
      <p className="text-xs text-gray-500 mb-4">
        Download a copy of your personal data (right to portability) or request account deletion.
      </p>

      {error && (
        <div className="mb-3 flex items-start gap-2 p-3 bg-red-50 border border-red-200 text-xs text-red-700">
          <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
          <span>{error}</span>
        </div>
      )}
      {success && (
        <div className="mb-3 flex items-start gap-2 p-3 bg-green-50 border border-green-200 text-xs text-green-700">
          <CheckCircle2 className="w-4 h-4 flex-shrink-0 mt-0.5" />
          <span>{success}</span>
        </div>
      )}

      <div className="flex flex-wrap gap-3">
        <button
          type="button"
          onClick={handleExport}
          disabled={exporting || deleting}
          className="inline-flex items-center gap-2 px-4 py-2 text-xs font-medium text-white bg-fuchsia hover:opacity-90 disabled:opacity-50 transition-opacity"
        >
          {exporting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
          Download my data
        </button>

        {!confirming ? (
          <button
            type="button"
            onClick={() => { setConfirming(true); setError(null); setSuccess(null); }}
            disabled={exporting || deleting}
            className="inline-flex items-center gap-2 px-4 py-2 text-xs font-medium text-red-700 border border-red-300 bg-white hover:bg-red-50 disabled:opacity-50 transition-colors"
          >
            <Trash2 className="w-3.5 h-3.5" />
            Delete my account
          </button>
        ) : (
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs text-red-700">This schedules permanent deletion in 30 days. Confirm?</span>
            <button
              type="button"
              onClick={handleDelete}
              disabled={deleting}
              className="inline-flex items-center gap-2 px-4 py-2 text-xs font-medium text-white bg-red-600 hover:bg-red-700 disabled:opacity-50 transition-colors"
            >
              {deleting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Trash2 className="w-3.5 h-3.5" />}
              Yes, delete
            </button>
            <button
              type="button"
              onClick={() => setConfirming(false)}
              disabled={deleting}
              className="px-4 py-2 text-xs font-medium text-gray-600 border border-gray-300 bg-white hover:bg-gray-50 disabled:opacity-50"
            >
              Cancel
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
