import React, { useState } from 'react';
import { Star, Target, Users, Brain, Heart, RefreshCw, FileText, Download, Edit3, Send, ChevronRight, Award, TrendingUp } from 'lucide-react';
import { Badge, Button, Card, Progress } from '@/components/ui';
import { CanvasRadarChart } from './CanvasRadarChart';

interface CanvasProfileViewProps {
  profile: any;
  trident?: any;
  contact?: any;
  onEdit?: () => void;
  onSendForReview?: () => void;
}

export function CanvasProfileView({ profile, trident, contact, onEdit, onSendForReview }: CanvasProfileViewProps) {
  const [expandedEvidence, setExpandedEvidence] = useState<string | null>(null);

  const canvasScores = {
    strategic_thinking: profile.c_strategic_thinking,
    communication: profile.c_communication,
    adaptability: profile.c_adaptability,
    team_leadership: profile.c_team_leadership,
    decision_making: profile.c_decision_making,
    emotional_intelligence: profile.c_emotional_intelligence,
  };

  const gradeColors: Record<string, string> = {
    'A+': 'bg-green-500',
    'A': 'bg-emerald-500',
    'B': 'bg-amber-500',
    'C': 'bg-orange-500',
    'F': 'bg-red-500',
  };

  const dimensionCards = [
    { key: 'strategic_thinking', label: 'Strategic Thinking', value: profile.c_strategic_thinking, icon: Target, color: 'bg-blue-50' },
    { key: 'communication', label: 'Communication', value: profile.c_communication, icon: Users, color: 'bg-green-50' },
    { key: 'adaptability', label: 'Adaptability', value: profile.c_adaptability, icon: RefreshCw, color: 'bg-purple-50' },
    { key: 'team_leadership', label: 'Team Leadership', value: profile.c_team_leadership, icon: Users, color: 'bg-indigo-50' },
    { key: 'decision_making', label: 'Decision Making', value: profile.c_decision_making, icon: Brain, color: 'bg-pink-50' },
    { key: 'emotional_intelligence', label: 'Emotional Intelligence', value: profile.c_emotional_intelligence, icon: Heart, color: 'bg-rose-50' },
  ];

  const narrativeCards = [
    { key: 'leadership_style', label: 'Leadership Style', content: profile.leadership_style },
    { key: 'key_strengths', label: 'Key Strengths', content: profile.key_strengths, isList: true },
    { key: 'blind_spots', label: 'Blind Spots', content: profile.blind_spots, isList: true },
    { key: 'derailment_risks', label: 'Derailment Risks', content: profile.derailment_risks, isList: true },
    { key: 'impact_potential', label: 'Impact Potential', content: profile.impact_potential },
    { key: 'stakeholder_style', label: 'Stakeholder Style', content: profile.stakeholder_style },
    { key: 'development_journey', label: 'Development Journey', content: profile.development_journey },
    { key: 'priority_focus_areas', label: 'Priority Focus Areas', content: profile.priority_focus_areas, isList: true },
  ];

  const reviewStatusColors: Record<string, string> = {
    pending: 'bg-yellow-100 text-yellow-700',
    approved: 'bg-green-100 text-green-700',
    edits_requested: 'bg-orange-100 text-orange-700',
    edited: 'bg-blue-100 text-blue-700',
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">
            CANVAS Profile — {contact?.full_name || 'Candidate'}
          </h1>
          <div className="flex items-center gap-4 mt-2 text-sm text-gray-500">
            <span>Generated by: {profile.generated_by_name || 'Unknown'}</span>
            <span>|</span>
            <span>{new Date(profile.created_at).toLocaleDateString()}</span>
            <Badge className={reviewStatusColors[profile.review_status] || 'bg-gray-100 text-gray-700'}>
              {profile.review_status === 'pending' ? '⏳ Pending Review' : profile.review_status}
            </Badge>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={onEdit}>
            <Edit3 className="mr-2" />
            Edit
          </Button>
          <Button variant="outline" onClick={onSendForReview} disabled={profile.review_status !== 'pending'}>
            <Send className="mr-2" />
            Send for Review
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="p-6">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="w-5 h-5 text-blue-600" />
            <h3 className="font-semibold text-gray-800">TRIDENT Assessment</h3>
          </div>
          {trident ? (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-gray-600">Composite</span>
                <span className="text-xl font-bold text-gray-800">{trident.composite_score}/10</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-600">Verdict</span>
                <Badge className={trident.verdict === 'Exceptional Primary' || trident.verdict === 'Strong' ? 'bg-green-100 text-green-700' : trident.verdict === 'Solid' ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-700'}>
                  {trident.verdict}
                </Badge>
              </div>
              <div className="space-y-3 mt-4">
                <div>
                  <div className="flex justify-between text-sm mb-1">
                    <span className="text-gray-500">D1: Domain & Intelligence</span>
                    <span className="font-medium">{trident.d1_score}/10</span>
                  </div>
                  <Progress value={(trident.d1_score / 10) * 100} className="h-2" />
                </div>
                <div>
                  <div className="flex justify-between text-sm mb-1">
                    <span className="text-gray-500">D2: Delivery & Influence</span>
                    <span className="font-medium">{trident.d2_score}/10</span>
                  </div>
                  <Progress value={(trident.d2_score / 10) * 100} className="h-2" />
                </div>
                <div>
                  <div className="flex justify-between text-sm mb-1">
                    <span className="text-gray-500">D3: Drive & Dynamics</span>
                    <span className="font-medium">{trident.d3_score}/10</span>
                  </div>
                  <Progress value={(trident.d3_score / 10) * 100} className="h-2" />
                </div>
              </div>
            </div>
          ) : (
            <p className="text-gray-400 text-sm">TRIDENT scorecard not available</p>
          )}
        </Card>

        <Card className="p-6">
          <div className="flex items-center gap-2 mb-4">
            <Award className="w-5 h-5 text-purple-600" />
            <h3 className="font-semibold text-gray-800">CANVAS Assessment</h3>
          </div>
          <div className="flex items-center justify-between mb-4">
            <div>
              <div className="text-3xl font-bold text-gray-800">{profile.canvas_composite}/10</div>
              <div className="text-gray-500 text-sm">Composite Score</div>
            </div>
            <Badge className={`text-2xl px-6 py-3 ${gradeColors[profile.canvas_grade]} text-white font-bold`}>
              {profile.canvas_grade}
            </Badge>
          </div>
          <CanvasRadarChart scores={canvasScores} />
        </Card>

        <Card className="p-6">
          <div className="flex items-center gap-2 mb-4">
            <FileText className="w-5 h-5 text-gray-600" />
            <h3 className="font-semibold text-gray-800">Executive Summary</h3>
          </div>
          <p className="text-gray-700 leading-relaxed">{profile.executive_summary || 'Not yet generated'}</p>
          <Button variant="outline" className="w-full mt-4" onClick={() => window.open(profile.pdf_url, '_blank')} disabled={!profile.pdf_url}>
            <Download className="mr-2" />
            Download PDF
          </Button>
        </Card>
      </div>

      <Card className="p-6">
        <h3 className="font-semibold text-gray-800 mb-4">CANVAS Dimension Scores</h3>
        <div className="grid grid-cols-2 lg:grid-cols-3 gap-4">
          {dimensionCards.map((dim) => (
            <div key={dim.key} className={`p-4 rounded-lg ${dim.color}`}>
              <div className="flex items-center gap-2 mb-2">
                <dim.icon className="w-4 h-4 text-gray-600" />
                <span className="text-sm font-medium text-gray-700">{dim.label}</span>
              </div>
              <div className="text-2xl font-bold text-gray-800">{dim.value}/10</div>
              <Progress value={(dim.value / 10) * 100} className="h-2 mt-2" />
            </div>
          ))}
        </div>
      </Card>

      <Card className="p-6">
        <h3 className="font-semibold text-gray-800 mb-4">Executive Profile</h3>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {narrativeCards.map((card) => (
            <div key={card.key} className="p-4 bg-gray-50 rounded-lg">
              <div className="font-medium text-gray-700 mb-2">{card.label}</div>
              {card.isList && Array.isArray(card.content) ? (
                <ul className="space-y-1">
                  {card.content.map((item: string, index: number) => (
                    <li key={index} className="text-sm text-gray-600 flex items-start gap-2">
                      <span className="text-blue-600">•</span>
                      {item}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-sm text-gray-600">{card.content}</p>
              )}
            </div>
          ))}
        </div>
      </Card>

      {trident && (
        <Card className="p-6">
          <h3 className="font-semibold text-gray-800 mb-4">TRIDENT Evidence</h3>
          <div className="space-y-4">
            <div className="border-b pb-4">
              <button
                onClick={() => setExpandedEvidence(expandedEvidence === 'd1' ? null : 'd1')}
                className="flex items-center justify-between w-full text-left"
              >
                <span className="font-medium text-gray-700">D1: Domain & Intelligence</span>
                <ChevronRight className={`w-4 h-4 transition-transform ${expandedEvidence === 'd1' ? 'rotate-90' : ''}`} />
              </button>
              {expandedEvidence === 'd1' && (
                <p className="text-sm text-gray-600 mt-2">{trident.d1_evidence}</p>
              )}
            </div>
            <div className="border-b pb-4">
              <button
                onClick={() => setExpandedEvidence(expandedEvidence === 'd2' ? null : 'd2')}
                className="flex items-center justify-between w-full text-left"
              >
                <span className="font-medium text-gray-700">D2: Delivery & Influence</span>
                <ChevronRight className={`w-4 h-4 transition-transform ${expandedEvidence === 'd2' ? 'rotate-90' : ''}`} />
              </button>
              {expandedEvidence === 'd2' && (
                <p className="text-sm text-gray-600 mt-2">{trident.d2_evidence}</p>
              )}
            </div>
            <div>
              <button
                onClick={() => setExpandedEvidence(expandedEvidence === 'd3' ? null : 'd3')}
                className="flex items-center justify-between w-full text-left"
              >
                <span className="font-medium text-gray-700">D3: Drive & Dynamics</span>
                <ChevronRight className={`w-4 h-4 transition-transform ${expandedEvidence === 'd3' ? 'rotate-90' : ''}`} />
              </button>
              {expandedEvidence === 'd3' && (
                <p className="text-sm text-gray-600 mt-2">{trident.d3_evidence}</p>
              )}
            </div>
          </div>
        </Card>
      )}
    </div>
  );
}
