-- P1-2 — Chat document upload + RAG context injection
--
-- Stores chunked text extracted from user-uploaded documents (PDF/DOCX/TXT)
-- so the chat backend can inject relevant context into the NEXUS system
-- prompt. Frontend uploads files to the `chat-uploads` Storage bucket at
-- path `{user_id}/{session_id}/{filename}`; the worker downloads the file,
-- extracts text, chunks it (~500 chars w/ 100 overlap), and inserts rows
-- here under the caller's user_id.
--
-- RLS:
--   • SELECT/INSERT/DELETE = owner only (auth.uid() = user_id)
--   • Service role (worker) bypasses RLS for chunk writes
--
-- Storage bucket `chat-uploads`:
--   • public-read OFF, per-user RLS policies (owner can CRUD own path)

-- ════════════════════════════════════════════════════════════════════
--  1. Storage bucket: chat-uploads
-- ════════════════════════════════════════════════════════════════════
-- Insert idempotently; if the bucket already exists this is a no-op.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'chat-uploads',
  'chat-uploads',
  false,                                  -- private — RLS-gated
  10 * 1024 * 1024,                       -- 10 MB cap (matches UI)
  ARRAY[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'text/plain'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS — owner-only CRUD on {user_id}/... paths.
-- Supabase Storage policies live on the `storage.objects` table.

DROP POLICY IF EXISTS chat_uploads_owner_select ON storage.objects;
CREATE POLICY chat_uploads_owner_select ON storage.objects
  FOR SELECT
  USING (
    bucket_id = 'chat-uploads'
    AND (storage.foldername(name))[1] = (auth.uid())::text
  );

DROP POLICY IF EXISTS chat_uploads_owner_insert ON storage.objects;
CREATE POLICY chat_uploads_owner_insert ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'chat-uploads'
    AND (storage.foldername(name))[1] = (auth.uid())::text
  );

DROP POLICY IF EXISTS chat_uploads_owner_update ON storage.objects;
CREATE POLICY chat_uploads_owner_update ON storage.objects
  FOR UPDATE
  USING (
    bucket_id = 'chat-uploads'
    AND (storage.foldername(name))[1] = (auth.uid())::text
  );

DROP POLICY IF EXISTS chat_uploads_owner_delete ON storage.objects;
CREATE POLICY chat_uploads_owner_delete ON storage.objects
  FOR DELETE
  USING (
    bucket_id = 'chat-uploads'
    AND (storage.foldername(name))[1] = (auth.uid())::text
  );

-- ════════════════════════════════════════════════════════════════════
--  2. chat_document_chunks table
-- ════════════════════════════════════════════════════════════════════
-- One row per chunk. `document_id` groups all chunks from a single uploaded
-- file (UUID generated by the worker); the worker returns it to the client
-- and the client sends it back as `document_ids: [...]` on subsequent chat
-- messages so the backend can fetch + inject context.

CREATE TABLE IF NOT EXISTS chat_document_chunks (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id    TEXT,
  document_id   UUID NOT NULL,
  filename      TEXT NOT NULL,
  content_type  TEXT,
  chunk_index   INTEGER NOT NULL,
  content       TEXT NOT NULL,
  char_count    INTEGER,
  storage_path  TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(document_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_chat_document_chunks_user_session
  ON chat_document_chunks(user_id, session_id);
CREATE INDEX IF NOT EXISTS idx_chat_document_chunks_document
  ON chat_document_chunks(document_id, chunk_index);

-- ════════════════════════════════════════════════════════════════════
--  3. RLS — owner only
-- ════════════════════════════════════════════════════════════════════

ALTER TABLE chat_document_chunks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS chat_document_chunks_owner_select ON chat_document_chunks;
CREATE POLICY chat_document_chunks_owner_select ON chat_document_chunks
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS chat_document_chunks_owner_insert ON chat_document_chunks;
CREATE POLICY chat_document_chunks_owner_insert ON chat_document_chunks
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS chat_document_chunks_owner_delete ON chat_document_chunks;
CREATE POLICY chat_document_chunks_owner_delete ON chat_document_chunks
  FOR DELETE USING (auth.uid() = user_id);

-- (No UPDATE policy — chunks are immutable once written; the worker uses
-- the service role key to insert, which bypasses RLS.)
