/**
 * schemas/aiGeneratedContent.ts — #97 CONTRACT for ALL AI-generated content output
 * Covers: #96 engine, #100 triggers (manual/auto/scheduled), #1343 AI insights blocks
 *
 * Everything NEXUS writes into a report / email MUST pass through this shape
 * so brand voice + tier + audit can be enforced at a single boundary.
 */

import type { NexusIntent } from '@/nexus/intentClassifier';

/** Provenance chain for audit — every generated block carries this. */
export interface AiContentProvenance {
  /** Unique generation ID (audit trace) */
  generation_id: string;
  /** Template / intent this was generated for */
  intent: NexusIntent | 'assessment_summary' | 'weekly_digest' | 'monthly_summary' | '3day_checkin' | 'share_note';
  /** DeepSeek model used — or 'template' for deterministic (no LLM) */
  model_used: 'deepseek-flash' | 'deepseek-pro' | 'template-generated';
  /** API cost cents (USD * 100) — 0 if template-generated */
  cost_cents: number;
  /** Miles debited from user balance (1 per Flash, 3 per Pro) */
  miles_debited: 0 | 1 | 3;
  /** User tier at generation time (for audit history on tier upgrades) */
  user_tier: string;
  /** Brand guard pass/fail + list of warnings (never fails hard — soft-warns) */
  brand_guard: {
    passes: boolean;
    hard_violations: number;
    soft_violations: number;
    issues: Array<{ severity: 'error' | 'warn'; category: string; snippet: string }>;
  };
  /** Version of system prompt + templates used (future regeneration) */
  prompt_config_version: string;
  /** ISO timestamp */
  generated_at: string;
  /** Token usage */
  tokens: { prompt: number; completion: number; total: number };
  /** Human author override (if this content was edited by a consultant) */
  human_author?: { user_id: string; name: string; edited_at: string };
}

/** Confidence tier for AI content — surfaced to Executive Introduction users as "AI preview" */
export type AiConfidence = 'low' | 'medium' | 'high' | 'human_verified';

/** Individual generated insight — smallest atomic unit */
export interface AiContentBlock {
  /** Stable ID for this insight (referenced in redactions, audits, feedback) */
  block_id: string;
  kind:
    | 'summary_paragraph'
    | 'strength'
    | 'growth_area'
    | 'next_step'
    | 'dimension_insight'
    | 'archetype_narrative'
    | 'share_cover_note'
    | 'weekly_digest_body'
    | 'chat_reflection';
  /** Generated text (final displayed copy) */
  content: string;
  /** Associated dimension or archetype key */
  anchor_key?: string;
  /** Confidence — Executive Introduction sees "medium" and below labeled as PREVIEW */
  confidence: AiConfidence;
  /** RAG citations referenced (from content library) */
  citations?: Array<{ content_id: string; title: string; source_type: string }>;
  /** End-user feedback thumbs (0 = none, 1 = helpful, -1 = not helpful) */
  feedback?: -1 | 0 | 1;
  /** Provenance — attached to every block */
  provenance: AiContentProvenance;
  /** If true, this block is hidden at Executive Introduction tier */
  requires_tier?: 'professional' | 'executive' | 'council' | 'enterprise';
}

/** Contract for AI-generated insights embedded into AssessmentResultSchema.ai_insights */
export interface AiGeneratedInsightBundle {
  readonly contract_version: 'ai.v1';
  summary: AiContentBlock;                          // kind = summary_paragraph
  strengths: AiContentBlock[];                       // kind = strength (2-3 items)
  growth_areas: AiContentBlock[];                    // kind = growth_area (2-3 items)
  next_steps: AiContentBlock[];                      // kind = next_step (3-4 items)
  dimension_insights?: Record<string, AiContentBlock>; // key = dimension_key
  archetype_narrative?: AiContentBlock;              // kind = archetype_narrative
  /** Aggregate stats — rendered in the "Generated by NEXUS" disclosure line */
  _meta: {
    miles_spent_total: number;
    dollars_spent_cents: number;
    total_tokens: number;
    has_human_overrides: boolean;
    passes_brand_guard: boolean;
    generated_at: string;
  };
}

/* ── Type guards ────────────────────────────────────────────────── */

export function isAiBlock(v: unknown): v is AiContentBlock {
  if (!v || typeof v !== 'object') return false;
  const b = v as AiContentBlock;
  return typeof b.block_id === 'string'
    && typeof b.kind === 'string'
    && typeof b.content === 'string'
    && typeof b.confidence === 'string'
    && typeof b.provenance === 'object';
}

/**
 * Filter an AiGeneratedInsightBundle to a given viewer tier.
 * Removes blocks that require a tier the viewer doesn't have.
 * Returns NEW object (never mutates input).
 */
export function redactAiBundleForTier<T extends TierLike>(bundle: AiGeneratedInsightBundle, viewerTier: T): AiGeneratedInsightBundle {
  // Tier hierarchy (index higher = more capabilities). Order must match TIER_KEYS in tierConfig.
  const order = ['executive_introduction', 'professional', 'executive', 'council', 'enterprise'];
  const viewerIdx = order.indexOf(String(viewerTier));

  const ok = <B extends AiContentBlock>(b: B): boolean => {
    if (!b.requires_tier) return true;
    const needIdx = order.indexOf(b.requires_tier);
    return viewerIdx >= needIdx;
  };

  return {
    ...bundle,
    summary: bundle.summary,
    strengths: bundle.strengths.filter(ok),
    growth_areas: bundle.growth_areas.filter(ok),
    next_steps: bundle.next_steps.filter(ok),
    dimension_insights: bundle.dimension_insights
      ? Object.fromEntries(Object.entries(bundle.dimension_insights).filter(([, b]) => ok(b)))
      : undefined,
    archetype_narrative: bundle.archetype_narrative && ok(bundle.archetype_narrative)
      ? bundle.archetype_narrative
      : undefined,
    _meta: bundle._meta,
  };
}

type TierLike = 'executive_introduction' | 'professional' | 'executive' | 'council' | 'enterprise' | (string & {});
