"""
FORGE Dimension Content Library — Gold Standard Narratives
FORGE: Organisational Diagnostic Assessment
Business-oriented, APAC-calibrated, Hogan/DISC-quality depth.
"""

FORGE_DIMENSIONS = {
    "ADAPTIVE LEARNING ORIENTATION (ALO)": {
    "id": "D1",
    "construct": "Sales Excellence & Revenue Architecture - ADAPTIVE LEARNING ORIENTATION (ALO)",
    "description": [
        "Adaptive Learning Orientation measures a leader's capacity to systematically update their sales approach in response to market shifts, competitive dynamics, and organisational changes. This dimension is critical because revenue sustainability depends not on a single winning playbook but on the organisation's ability to evolve its playbook continuously. Leaders with high ALO treat learning as a structural capability, not a personal trait, and embed feedback loops into revenue systems. Without this, sales organisations ossify, relying on outdated assumptions while competitors exploit new gaps.",
        "At the organisational level, ALO determines whether the sales function learns as a system or merely as a collection of individuals. A leader with high ALO designs mechanisms—such as quarterly market sensing reviews, win/loss analysis protocols, and adaptive incentive structures—that institutionalise learning across the revenue engine. This shifts the organisation from reactive pattern recognition to proactive strategy recalibration, ensuring that revenue architecture remains relevant as markets evolve. The risk of low ALO is not just missed targets but systemic fragility: the organisation cannot pivot when its core assumptions are invalidated.",
        "In APAC contexts, ALO is particularly critical due to the region's high velocity of market change, regulatory shifts, and cultural heterogeneity. A leader who relies on a static playbook from a mature market like Singapore will fail in Indonesia's fragmented distribution landscape or Japan's relationship-intensive B2B cycles. Cross-border sales leaders must calibrate learning orientation to local market signals—for example, adapting pricing models in real-time as Southeast Asian currencies fluctuate—while maintaining coherence across the regional revenue architecture. The ability to learn from one market and apply insights to another without overgeneralising is a hallmark of high ALO in APAC."
    ],
    "sub_dim_interpretation": {
        "Market Signal Detection": "High scorers systematically scan for leading indicators of market change—such as shifts in buyer behaviour, regulatory announcements, or competitor moves—and integrate these into strategic planning. Low scorers rely on lagging indicators like quarterly results, missing inflection points until they become crises.",
        "Playbook Iteration Speed": "High scorers compress the cycle from insight to action, updating sales playbooks within weeks rather than quarters. Low scorers treat playbooks as fixed documents, creating a gap between market reality and sales execution.",
        "Failure Absorption & Learning": "High scorers design systems that capture lessons from lost deals and failed initiatives without blame, turning setbacks into organisational knowledge. Low scorers either ignore failures or punish them, suppressing the very data needed for adaptation.",
        "Cross-Market Knowledge Transfer": "High scorers create structured mechanisms—such as regional councils or shared case libraries—to transfer learning across markets without losing local nuance. Low scorers leave knowledge siloed, forcing each market to rediscover the same lessons.",
        "Adaptive Incentive Design": "High scorers align compensation and recognition with learning behaviours—rewarding experimentation, insight sharing, and playbook updates—not just outcome metrics. Low scorers incentivise only results, discouraging the risk-taking necessary for adaptation.",
        "Strategic Recalibration Cadence": "High scorers institutionalise a regular cadence of strategic reviews (e.g., quarterly market sensing offsites) that challenge core assumptions and reallocate resources. Low scorers review strategy annually or only in crisis, missing windows of opportunity."
    },
    "band_narratives": {
        "Strong (≥70%)": "Leaders at this level embed adaptive learning as a core operating principle of the revenue architecture. They design systems that detect market shifts early, update playbooks rapidly, and transfer insights across markets without losing local relevance. The organisational impact is a sales function that treats change as a constant and uses it as a competitive advantage. The specific risk at this level is over-adaptation: the organisation may pivot too frequently, creating confusion and undermining strategic coherence if not balanced with stability.",
        "Developing (50-69%)": "These leaders demonstrate personal learning agility but struggle to institutionalise it across the organisation. They may update their own approach based on market feedback but fail to design mechanisms that enable the broader sales team to adapt. The breakdown occurs when the leader is absent or overwhelmed: the organisation reverts to static playbooks. The development priority is shifting from individual learning to systemic learning by building feedback loops, playbook governance, and cross-market knowledge transfer processes.",
        "Gap (<50%)": "Leaders in this band rely on static playbooks and resist updating their approach even when market signals are clear. They may attribute underperformance to execution failures rather than outdated strategy, creating a culture of blame rather than learning. In business contexts, this manifests as declining win rates, missed market shifts, and a sales organisation that becomes increasingly irrelevant. The fundamental change needed is a shift in mindset from 'this is what works' to 'this is what works now'—supported by structural mechanisms that force regular recalibration."
    },
    "overuse_risks": "When Adaptive Learning Orientation is over-applied without counterbalance, the organisation becomes hyper-reactive, pivoting strategy with every market tremor and losing strategic coherence. This manifests as constant playbook changes that confuse the sales team, erode trust in leadership, and waste resources on abandoned initiatives. The organisational cost is a loss of focus: the revenue architecture becomes a series of tactical responses rather than a coherent system. Leaders must temper ALO with strategic conviction and clear decision-making criteria to avoid adaptation for its own sake.",
    "cross_dynamics": [
        {"dim": "Three Forces Awareness (TFA)", "interaction": "ALO and TFA are synergistic: high ALO enables a leader to learn from market, competitive, and organisational forces, while TFA provides the framework for what to monitor. Together, they create a sensing-and-responding system that is both comprehensive and adaptive. The risk is that high ALO without TFA leads to learning in the wrong areas, while high TFA without ALO produces analysis without action.", "risk": "low"},
        {"dim": "Development Agency (DA)", "interaction": "ALO and DA interact in a tension: high ALO drives continuous change, while DA focuses on building stable capability in others. Leaders must balance the need to update playbooks (ALO) with the need to develop people's mastery of current approaches (DA). Over-prioritising ALO can undermine DA by creating constant disruption that prevents skill consolidation.", "risk": "medium"},
        {"dim": "Bilateral Context Navigation (BCN)", "interaction": "ALO and BCN interact critically in cross-border contexts: high ALO enables a leader to learn from local market signals, while BCN provides the cultural and relational intelligence to adapt appropriately. Without BCN, ALO-driven changes may violate local norms or alienate key stakeholders. The synergy is that BCN ensures learning is contextually grounded, while ALO ensures it is continuously updated.", "risk": "medium"}
    ],
    "coaching_prompts": [
        "Describe a specific market signal you detected in the last quarter that led you to change your sales strategy. What was the signal, how did you validate it, and what did you change?",
        "Think of a recent lost deal that your team analysed. What systemic lesson was extracted, and how was that lesson embedded into the playbook for the next quarter?",
        "If you were to leave your role for six months, what mechanisms would ensure your sales organisation continues to adapt to market changes in your absence?",
        "Identify a playbook assumption you held six months ago that has since been invalidated. How did you discover this, and what is the cost of not having discovered it sooner?",
        "How do you ensure that learning from one market (e.g., Vietnam) is transferred to another (e.g., Thailand) without losing local relevance? Give a concrete example of a success or failure.",
        "What is the single most important metric you track to assess whether your sales organisation is learning and adapting, rather than just executing?"
    ],
    "apac_calibration": [
        "In high-growth APAC markets like Vietnam or Indonesia, ALO must operate at a faster cadence due to rapid market maturation and regulatory shifts. A leader who updates playbooks quarterly may still be too slow; monthly or even weekly recalibration may be necessary to capture emerging opportunities.",
        "In mature markets like Japan or South Korea, high ALO must be balanced with respect for established relationships and hierarchical decision-making. Rapid playbook changes can be perceived as instability, undermining trust. Leaders must frame adaptation as continuous improvement rather than disruption.",
        "Cross-border APAC leaders face the challenge of calibrating learning orientation to each market's velocity. A one-size-fits-all approach to playbook iteration speed will fail; leaders must design a tiered system where high-velocity markets (e.g., Singapore, India) have faster cycles than stable ones (e.g., Australia, New Zealand).",
        "In APAC, failure absorption is culturally nuanced: in some markets (e.g., China), failure is stigmatised, while in others (e.g., Australia), it is more accepted. Leaders must design learning systems that respect local cultural attitudes toward failure while still extracting insights—for example, using anonymous win/loss analysis in high-stigma contexts."
    ]
},

    "THREE FORCES AWARENESS (TFA)": {
    "id": "D2",
    "construct": "Sales Excellence & Revenue Architecture - THREE FORCES AWARENESS (TFA)",
    "description": [
        "This dimension measures a leader's capacity to perceive and integrate the three exogenous forces—market evolution, competitive positioning, and organisational capability—that collectively determine revenue sustainability. It is the cognitive foundation for revenue architecture: without systemic awareness of these forces, leaders default to tactical deal-making or reactive resource allocation, both of which erode margin and scalability. TFA is critical because it separates those who build resilient revenue systems from those who merely exploit transient personal relationships or market tailwinds. In enterprise sales leadership, this awareness directly predicts whether revenue growth is repeatable or episodic.",
        "At the organisational level, TFA operates as a strategic sensing mechanism: leaders strong in this dimension institutionalise processes for scanning market shifts, competitor moves, and internal capability gaps, then translate these insights into resource allocation decisions and sales system design. Weak TFA manifests as chronic misalignment between sales strategy and market reality—for example, investing heavily in a product line while customer demand is migrating to adjacent segments, or failing to build competitive differentiation because the leader cannot articulate how rivals are positioning. The organisational cost is not just missed revenue but systemic fragility: the revenue architecture becomes brittle, dependent on a few individuals or a single product cycle.",
        "In APAC contexts, TFA is particularly critical because market heterogeneity across countries—from mature Japan to high-growth Vietnam—demands nuanced force calibration. A leader who applies a Singapore-centric competitive analysis to Indonesia will misread both customer evolution and regulatory constraints, leading to flawed resource allocation. Additionally, the rapid pace of digital transformation in markets like China and India means competitive forces shift quarterly, not annually; leaders without TFA cannot adapt their revenue architecture fast enough to maintain relevance. Cross-border complexity amplifies the need for this dimension, as organisational forces (e.g., talent availability, partner ecosystems) vary dramatically across APAC jurisdictions."
    ],
    "sub_dim_interpretation": {
        "Market Force Perception": "High scorers accurately track customer evolution and sector shifts, using data to anticipate demand inflection points; low scorers rely on anecdotal feedback or lagging indicators, often missing structural market changes until revenue declines.",
        "Competitive Force Analysis": "High scorers map competitor positioning and market structure with precision, identifying both direct threats and adjacent disruptors; low scorers underestimate competitive intensity or focus only on known rivals, leaving the organisation vulnerable to asymmetric attacks.",
        "Organisational Force Calibration": "High scorers assess internal capability and resource allocation objectively, recognising when the organisation lacks the talent, process, or capital to execute strategy; low scorers overestimate internal readiness, leading to failed initiatives and wasted investment.",
        "Force Integration & Synthesis": "High scorers synthesise all three forces into coherent revenue architecture decisions—e.g., reallocating resources from a declining segment to an emerging one based on combined market, competitive, and capability data; low scorers treat forces in isolation, producing fragmented strategies.",
        "Strategic Foresight & Scenario Planning": "High scorers use force awareness to generate multiple revenue scenarios and stress-test the architecture against plausible futures; low scorers plan linearly, assuming current conditions persist, which leaves the organisation unprepared for disruption."
    },
    "band_narratives": {
        "Strong (≥70%)": "Leaders at this level demonstrate a disciplined, data-informed understanding of all three forces, enabling them to design revenue architecture that is both resilient and adaptive. They regularly update their force assessments, translating insights into concrete resource shifts and sales system adjustments—for example, reallocating sales headcount from a mature market to a high-growth adjacent sector based on competitive intelligence. The organisational impact is sustained revenue growth with lower volatility, as the architecture self-corrects in response to force changes. The specific risk at this level is over-analysis: these leaders may delay action while perfecting their force models, missing windows of opportunity in fast-moving markets.",
        "Developing (50-69%)": "These leaders grasp the importance of the three forces but apply them inconsistently—strong on market or competitive analysis but weak on organisational calibration, or vice versa. Their revenue architecture works in stable conditions but breaks down under disruption, such as a sudden competitor price war or a regulatory shift that exposes internal capability gaps. The development priority is to build systematic processes for force scanning and integration, moving from intuition-based to evidence-based decisions, and to close the weakest sub-dimension first.",
        "Gap (<50%)": "Leaders in this band operate with significant blind spots, often prioritising one force (e.g., market trends) while ignoring others (e.g., organisational readiness or competitive positioning). This manifests in business contexts as repeated strategic missteps—launching initiatives without the internal capability to execute, or failing to anticipate competitor moves until market share is lost. The organisational cost is severe: revenue architecture becomes reactive, resource allocation is misaligned, and the leader's personal relationships become the primary revenue driver, creating unsustainable dependency. The core need is foundational education in strategic sensing and a shift from tactical to systemic thinking."
    },
    "overuse_risks": "When over-applied, TFA leads to strategic paralysis: leaders become so consumed with scanning and analysing all three forces that they delay decision-making, waiting for perfect information that never arrives. This dysfunction shows up as a culture of analysis without action, where teams produce exhaustive competitive reports and market forecasts but fail to commit to resource allocation or sales system changes. The organisational cost is lost momentum—competitors who act on incomplete but timely information capture market share while the TFA-overloaded leader remains in diagnostic mode. Additionally, overuse can create a false sense of control, as leaders mistake awareness of forces for the ability to influence them, leading to overconfidence in strategic bets.",
    "cross_dynamics": [
        {"dim": "ADAPTIVE LEARNING ORIENTATION (ALO)", "interaction": "TFA provides the diagnostic input—what forces are shifting—while ALO drives the behavioural response: how quickly the leader updates mental models and adjusts revenue architecture. High TFA with low ALO produces accurate but static analysis, where the leader sees changes but fails to act on them; high ALO with low TFA leads to rapid but misdirected adaptation, as the leader changes course without understanding which forces truly matter. The synergy is powerful: TFA ensures the right data, ALO ensures the right response.", "risk": "high"},
        {"dim": "DEVELOPMENT AGENCY (DA)", "interaction": "TFA identifies organisational capability gaps (e.g., weak sales talent in a critical segment), while DA determines whether the leader actively develops those capabilities or simply documents the gap. High TFA with low DA results in accurate diagnosis without remediation—the leader knows the organisation is under-resourced but does not invest in building the required skills or systems. High DA with low TFA leads to capability building in the wrong areas, as the leader develops talent for a market or competitive reality that no longer exists.", "risk": "high"},
        {"dim": "BILATERAL CONTEXT NAVIGATION (BCN)", "interaction": "TFA focuses on external and internal forces at the market and organisational level, while BCN addresses the relational and cultural dynamics of cross-border stakeholder engagement. In APAC, these dimensions are interdependent: a leader with strong TFA may correctly identify a market opportunity in Thailand but fail to navigate the bilateral context—e.g., local partner expectations or government relationships—needed to execute. Conversely, strong BCN without TFA produces excellent relationships but poor strategic alignment, as the leader builds rapport in markets that are declining or misaligned with the revenue architecture.", "risk": "medium"}
    ],
    "coaching_prompts": [
        "Describe the last time you made a significant resource allocation decision—what specific data did you use about market trends, competitor moves, and your team's capability to execute?",
        "If you had to predict the biggest threat to your revenue architecture in the next 18 months, what would it be and which force—market, competitive, or organisational—is driving it?",
        "Walk me through your process for updating your understanding of customer evolution in your key APAC markets—how often do you do this, and what sources do you use?",
        "Think of a recent initiative that failed or underperformed—which of the three forces did you misread, and what would you have done differently with better awareness?",
        "How do you ensure that your competitive analysis includes not just direct rivals but adjacent disruptors or new entrants, particularly in fast-moving Asian markets?",
        "When you identify an organisational capability gap, what is your threshold for deciding whether to build internally, partner, or abandon the opportunity—and how do you calibrate that decision against market and competitive forces?"
    ],
    "apac_calibration": [
        "In markets like Japan and South Korea, where long-term relationships and consensus decision-making dominate, leaders may over-index on organisational forces (internal capability, hierarchy) while underweighting competitive forces, missing disruptive entrants that do not conform to traditional business norms.",
        "In high-growth Southeast Asian markets (e.g., Vietnam, Philippines), the rapid pace of customer evolution means market forces shift faster than competitive or organisational data can be gathered—leaders must calibrate to accept imperfect information and act on directional trends rather than waiting for full analysis.",
        "In China, the interplay between market forces and regulatory shifts (a subset of organisational forces at the macro level) is uniquely intense; leaders must integrate government policy changes as a fourth force, or risk building revenue architecture that is invalidated by a single regulatory announcement.",
        "Cross-border APAC leaders face the challenge of calibrating force weights differently per market—what is a critical competitive threat in India may be irrelevant in Australia—requiring a dynamic, portfolio-level TFA approach rather than a uniform framework."
    ]
},

    "DEVELOPMENT AGENCY (DA)": {
    "id": "D3",
    "construct": "Sales Excellence & Revenue Architecture - DEVELOPMENT AGENCY (DA)",
    "description": [
        "DEVELOPMENT AGENCY measures a leader's capacity to institutionalise sales capability — transforming revenue generation from a personality-dependent function into an organisational system. This dimension assesses whether the leader can systematically build team competence, design knowledge transfer mechanisms, and create scalable processes that enable the organisation to grow revenue independent of any single individual. It is the critical scalability dimension: without high DA, revenue architecture remains fragile, tied to the tenure and relationships of key players, and unable to sustain growth across market cycles or geographic expansion.",
        "At the organisational level, DA determines whether sales capability is a renewable asset or a depreciating liability. Leaders strong in DA invest in structured onboarding, continuous skill development, and performance management systems that elevate the entire team's effectiveness. They create feedback loops where market intelligence flows from frontline interactions into strategy, and where best practices are codified and disseminated. The organisational cost of low DA is visible in revenue plateaus, high turnover of top performers, and an inability to replicate success in new territories or segments — the classic 'founder-led sales' trap that limits enterprise value.",
        "In APAC markets, DA is particularly critical due to the prevalence of relationship-driven sales cultures and the rapid pace of market evolution. Leaders must navigate the tension between leveraging personal networks (which are often essential for initial market entry) and building institutional capability that can outlast individual relationships. The cross-border dimension adds complexity: a leader who can develop sales capability in one Asian market may struggle to transfer that knowledge across linguistic, regulatory, and cultural boundaries. High DA in APAC requires deliberate investment in local talent pipelines, adaptive training that respects cultural nuances, and systems that capture tacit market knowledge before it walks out the door."
    ],
    "sub_dim_interpretation": {
        "Systematic Skill Transfer": "High scores indicate the leader actively designs and implements structured training, mentoring, and documentation processes that ensure sales competencies are consistently transferred across the team. Low scores reflect reliance on ad-hoc, informal knowledge sharing that leaves capability gaps and creates dependency on individual performers.",
        "Performance Architecture": "High scores reflect the leader's ability to build performance management systems — including metrics, dashboards, and review cadences — that drive accountability and continuous improvement. Low scores manifest as vague expectations, inconsistent feedback, and a reactive approach to underperformance.",
        "Talent Pipeline Development": "High scores show deliberate investment in identifying, nurturing, and promoting internal sales talent, creating a bench of future leaders. Low scores result in reliance on external hires, high turnover, and a lack of succession depth in critical revenue roles.",
        "Knowledge Codification": "High scores mean the leader systematically captures market intelligence, deal insights, and competitive data into reusable assets (playbooks, CRM notes, case studies). Low scores leave critical knowledge locked in individuals' heads, lost when they leave or move roles.",
        "Coaching Culture": "High scores indicate the leader embeds coaching as a daily practice — not a quarterly event — with managers trained to develop their teams through observation, feedback, and guided practice. Low scores reflect a culture of telling rather than teaching, where feedback is rare or punitive.",
        "Scalability Mindset": "High scores show the leader prioritises building systems and processes that allow revenue growth without proportional increases in headcount or founder time. Low scores reveal a preference for direct involvement in deals, creating bottlenecks and limiting organisational scale."
    },
    "band_narratives": {
        "Strong (≥70%)": "Leaders at this level build sales organisations that consistently outperform market averages, with predictable revenue growth driven by institutional capability rather than individual heroics. They create self-sustaining learning systems where new hires ramp quickly, top performers continuously improve, and the organisation adapts to market shifts without losing momentum. The primary risk at this level is over-engineering — investing so heavily in process and documentation that agility is sacrificed, and the sales team becomes bureaucratic rather than responsive.",
        "Developing (50-69%)": "These leaders demonstrate genuine commitment to development but struggle with consistency and depth. They may run effective training programs but fail to embed coaching into daily management, or they build good systems for one region but cannot replicate them across markets. The development priority is moving from episodic to systemic capability building — ensuring that development is not a project but a permanent organisational rhythm, and that knowledge transfer mechanisms are robust enough to survive leadership changes.",
        "Gap (<50%)": "Leaders in this band are typically strong individual contributors who have been promoted without developing the skills to build capability in others. They rely on their own deal-closing ability, hoard relationships, and create dependency that limits organisational growth. The business impact is severe: revenue stalls when the leader is unavailable, turnover of junior talent is high due to lack of development, and the organisation cannot scale into new markets or segments. The fundamental shift required is from 'doing' to 'enabling' — a change in identity as much as skill."
    },
    "overuse_risks": "When DA is over-applied, the organisation becomes process-heavy and innovation-light. Leaders may prioritise system compliance over adaptive selling, creating a rigid sales machine that cannot respond to unique customer needs or market anomalies. The cost is lost deals that require judgment, creativity, or relationship-based navigation — the very capabilities that DA seeks to institutionalise. In APAC contexts, overuse can manifest as excessive standardisation that ignores local relationship norms, alienating key clients and partners who expect personalised engagement."
    ,
    "cross_dynamics": [
        {"dim": "ADAPTIVE LEARNING ORIENTATION (ALO)", "interaction": "High DA combined with high ALO creates a learning organisation that systematically captures and applies market feedback — the ideal for sustainable revenue growth. Low ALO with high DA produces rigid systems that become obsolete as markets evolve, while high ALO with low DA results in learning that never scales beyond the individual leader.", "risk": "medium"},
        {"dim": "THREE FORCES AWARENESS (TFA)", "interaction": "DA provides the mechanism to operationalise TFA insights — building team capability to respond to market, competitive, and organisational forces. Without TFA, DA efforts may focus on the wrong capabilities, building systems that address yesterday's challenges. The synergy is powerful: TFA identifies what to develop, DA determines how to develop it at scale.", "risk": "medium"},
        {"dim": "BILATERAL CONTEXT NAVIGATION (BCN)", "interaction": "DA and BCN together enable leaders to build sales capability that is locally relevant yet globally consistent — critical for cross-border revenue architecture. High DA with low BCN produces standardised systems that fail in diverse markets, while high BCN with low DA results in fragmented local excellence that cannot be replicated. The tension is between standardisation and adaptation, requiring deliberate calibration.", "risk": "high"}
    ],
    "coaching_prompts": [
        "Describe a specific instance where you systematically transferred a sales skill or insight to a team member. What was the outcome, and what would you do differently?",
        "If you were unexpectedly absent for six months, which revenue relationships or capabilities would be at risk, and what systems could you build now to mitigate that?",
        "Walk me through your current process for onboarding a new sales hire. Where does the system break down, and what is the cost of that breakdown?",
        "Identify one sales process or knowledge asset that exists only in your head. What is the business case for codifying it, and what is stopping you?",
        "How do you currently measure the effectiveness of your sales development efforts? What would a leading indicator of capability growth look like in your context?",
        "Think of a top performer who left your team. What institutional knowledge was lost, and what system could have captured it before their departure?"
    ],
    "apac_calibration": [
        "In markets like Japan and Korea, where seniority and hierarchy shape learning dynamics, DA must be adapted to respect formal structures while still enabling genuine skill transfer. Leaders who impose Western-style coaching models may face resistance; effective DA in these contexts uses senior leaders as formal mentors and embeds development within existing career progression frameworks.",
        "In high-growth Southeast Asian markets (e.g., Vietnam, Indonesia, Philippines), the talent pool is often young and rapidly developing. DA here requires heavy investment in foundational sales skills and local language training, with systems that can scale across diverse educational backgrounds and cultural norms around feedback and authority.",
        "In China, the tension between guanxi (relationship networks) and institutional capability is acute. Leaders must build DA systems that capture and transfer relationship intelligence without undermining the personal trust that drives business. This requires careful design of CRM usage, team-based account management, and knowledge sharing protocols that respect the value of individual connections.",
        "Across APAC, the prevalence of family-owned businesses and founder-led enterprises means DA often requires a cultural shift from 'the leader knows best' to 'the system enables success.' Coaching must address the identity shift required for founders to delegate and institutionalise, which is often the hardest transition in scaling Asian businesses."
    ]
},

    "BILATERAL CONTEXT NAVIGATION (BCN)": {
    "id": "D4",
    "construct": "Sales Excellence & Revenue Architecture - BILATERAL CONTEXT NAVIGATION (BCN)",
    "description": [
        "BILATERAL CONTEXT NAVIGATION (BCN) measures a leader's capacity to architect and execute revenue strategies across asymmetric organisational, cultural, and institutional environments between seller and buyer. This dimension is critical because in cross-border sales, the revenue architecture must absorb friction from divergent governance models, decision-making hierarchies, and trust-building protocols—not merely translate language or adjust etiquette. BCN assesses whether a leader can systematically design sales processes that pre-empt bilateral friction, rather than relying on personal relationships or ad hoc cultural fixes. Without BCN, revenue architecture collapses under the weight of unmanaged contextual asymmetry, particularly in markets where institutional voids or relational economies dominate.",
        "At the organisational level, BCN determines whether a sales system can scale across borders without requiring the founder or senior leader to personally mediate every cross-context deal. A high-BCN leader builds revenue architecture that codifies bilateral navigation into playbooks, onboarding, and deal review cadences—for example, embedding 'decision-chain mapping' as a standard step in opportunity qualification for Japanese or Korean accounts. This dimension also governs how the organisation allocates resources: low-BCN leaders over-invest in relationship-building without structural rigour, while high-BCN leaders balance relational investment with systemic leverage, such as using local partner ecosystems to bridge institutional gaps. The organisational cost of low BCN is chronic deal slippage, misaligned revenue forecasts, and a sales force that burns out from context-switching without a framework.",
        "In APAC, BCN is the single most underrated dimension in revenue architecture because the region's default mode is cross-border selling—yet most sales systems are designed for mono-context environments like the US or EU. A leader strong in BCN recognises that selling from Singapore into Indonesia requires navigating different regulatory enforcement, trust currencies (e.g., gotong royong reciprocity), and decision velocity than selling from Hong Kong into mainland China. Without BCN, APAC revenue architecture defaults to either over-standardisation (ignoring local context) or over-customisation (destroying scalability). The highest-performing APAC revenue systems use BCN to create 'contextual templates'—repeatable frameworks that adapt to bilateral asymmetry without reinventing the wheel for every deal."
    ],
    "sub_dim_interpretation": {
        "Institutional Asymmetry Mapping": "High scores indicate the leader systematically identifies and codifies differences in legal, regulatory, and governance environments between buyer and seller contexts, embedding these into deal qualification criteria. Low scores reflect a tendency to treat all markets as institutionally equivalent, leading to compliance surprises or stalled approvals.",
        "Relational Currency Calibration": "High scores reflect the ability to discern and leverage the specific trust-building mechanisms (e.g., guanxi, wa, cronyism vs. contract-based trust) required in each bilateral context, and to design sales processes that align with these currencies. Low scores default to a single relational model, causing misalignment and lost credibility.",
        "Decision Hierarchy Decoding": "High scores indicate the leader can map and influence multi-layered decision-making structures in the buyer's organisation, including hidden veto points and consensus thresholds, and integrate this into revenue architecture. Low scores treat all buyer organisations as flat or transparent, leading to stalled deals and misallocated sales effort.",
        "Cultural Friction Absorption": "High scores reflect the design of sales systems that pre-emptively absorb cultural friction through structured protocols (e.g., meeting formats, escalation paths, communication cadences) rather than relying on individual adaptability. Low scores leave friction to be managed ad hoc, causing inconsistency and team burnout.",
        "Cross-Border Resource Allocation": "High scores indicate the leader allocates sales resources (time, budget, talent) proportionally to the complexity of each bilateral context, not just deal size or pipeline volume. Low scores allocate uniformly, over-investing in simple contexts and under-investing in complex ones, creating revenue leakage."
    },
    "band_narratives": {
        "Strong (≥70%)": "A leader at this level builds revenue architecture that treats bilateral context as a design parameter, not an exception. They embed institutional mapping, relational calibration, and decision decoding into standard operating procedures, enabling the sales force to navigate cross-border deals with repeatable rigour. The organisational impact is predictable revenue flow across markets, reduced deal cycle time, and a sales team that operates with contextual fluency rather than anxiety. The specific risk at this level is over-engineering—creating so many contextual protocols that the system becomes rigid and slows down in fast-moving opportunities.",
        "Developing (50-69%)": "This leader demonstrates strong situational awareness of bilateral differences but relies heavily on personal intervention or a small cadre of experienced managers to navigate them. The revenue architecture works in familiar contexts (e.g., Singapore-Malaysia) but breaks down in unfamiliar ones (e.g., Vietnam-India). The development priority is to codify their tacit knowledge into scalable frameworks and to build team capability in context navigation, rather than remaining the sole bridge. Without this shift, the organisation remains dependent on the leader's personal bandwidth, limiting geographic expansion.",
        "Gap (<50%)": "A leader in this band treats all sales contexts as functionally equivalent, applying a one-size-fits-all revenue architecture that ignores institutional, relational, and decision-making asymmetries. This manifests as chronic deal slippage in cross-border opportunities, misread buyer signals, and a sales force that either over-relies on local partners or burns out from repeated cultural missteps. The organisation needs immediate investment in contextual intelligence—starting with structured debriefs of lost cross-border deals and building a 'context profile' for each target market before scaling sales activity."
    },
    "overuse_risks": "When BCN is over-applied, the leader becomes hyper-attuned to context differences to the point of paralysis—every deal is treated as uniquely complex, requiring bespoke processes that destroy scalability and slow decision velocity. The organisation develops a 'contextual perfectionism' where sales teams spend disproportionate time analysing buyer environments rather than executing, leading to missed windows and competitor capture. The organisational cost is a revenue architecture that is so customised it cannot be replicated, and a culture that excuses underperformance by citing contextual complexity. The antidote is to balance BCN with ADAPTIVE LEARNING ORIENTATION (ALO), using rapid experimentation to test which contextual factors actually matter for deal outcomes versus which are noise.",
    "cross_dynamics": [
        {"dim": "ADAPTIVE LEARNING ORIENTATION (ALO)", "interaction": "BCN provides the contextual intelligence that ALO uses to design rapid experiments—without BCN, ALO experiments are run in a contextual vacuum, yielding misleading results. Conversely, ALO prevents BCN from becoming static by continuously testing and updating contextual assumptions. The synergy creates a revenue architecture that is both context-aware and agile.", "risk": "medium"},
        {"dim": "THREE FORCES AWARENESS (TFA)", "interaction": "BCN deepens TFA by revealing how market, competitive, and organisational forces manifest differently across bilateral contexts—for example, a competitor's strength in Japan may be irrelevant in Vietnam. Without BCN, TFA remains abstract and mono-contextual. The tension arises when BCN over-emphasises context at the expense of recognising universal competitive patterns.", "risk": "low"},
        {"dim": "DEVELOPMENT AGENCY (DA)", "interaction": "BCN identifies the specific contextual gaps that DA must address in building sales capability—for instance, training teams on Indonesian decision hierarchies versus Chinese guanxi protocols. Without BCN, DA investments are misdirected, developing generic skills that fail in specific bilateral contexts. The risk is that BCN without DA creates awareness without action, leaving the organisation knowing what to do but unable to execute.", "risk": "high"}
    ],
    "coaching_prompts": [
        "Describe a cross-border deal that stalled or failed—what specific contextual asymmetry (institutional, relational, or decision-making) do you now believe was the root cause, and how would you redesign your revenue architecture to prevent it?",
        "If you had to codify your personal approach to navigating a specific bilateral context (e.g., selling from Singapore to Indonesia) into a three-step protocol for a junior salesperson, what would those steps be—and where would the protocol likely break?",
        "Map the decision hierarchy of your last major cross-border buyer—who had veto power, who had influence but no formal authority, and how did your sales process account for each layer? What would you change?",
        "In which APAC market do you consistently over-invest relationship-building relative to deal value, and what structural change to your resource allocation model would correct this?",
        "What is one contextual assumption you hold about a key buyer market that, if wrong, would significantly change your revenue forecast—and how could you test that assumption in the next 30 days?",
        "Your sales team is struggling in a new bilateral context—describe the specific friction they are encountering and whether it is institutional, relational, or decision-hierarchy based. What systemic fix would you implement rather than coaching individuals?"
    ],
    "apac_calibration": [
        "In high-context markets like Japan and Korea, BCN must prioritise 'decision hierarchy decoding' over relational calibration—Western leaders often over-invest in relationship-building when the real bottleneck is understanding the ringi or jang consensus systems. Calibrate by mapping decision velocity against relationship depth in deal reviews.",
        "In Southeast Asia (e.g., Indonesia, Thailand), BCN must account for institutional voids and regulatory unpredictability—a strong leader builds 'regulatory buffer' into revenue architecture, such as parallel deal tracks for different enforcement scenarios. Calibrate by tracking how often deals are restructured due to regulatory changes.",
        "In China, BCN requires distinguishing between state-owned enterprise (SOE) and private sector contexts—the relational currency, decision timeline, and compliance requirements are fundamentally different. Calibrate by segmenting revenue architecture by buyer ownership type, not just industry.",
        "In India, BCN must navigate extreme heterogeneity across states (e.g., Tamil Nadu vs. Maharashtra) in terms of business culture, regulatory enforcement, and labour dynamics. Calibrate by building state-level context profiles and testing whether sales playbooks need to vary by more than 20% across regions."
    ]
},

}



def get_dimension_content(dim_name: str, score_pct: float) -> dict:
    """Get gold-standard content for a dimension, with score-band selection."""
    dim_data = FORGE_DIMENSIONS.get(dim_name)
    if not dim_data:
        return None
    
    if score_pct >= 70:
        band_key = "Strong (>=70%)"
    elif score_pct >= 50:
        band_key = "Developing (50-69%)"
    else:
        band_key = "Gap (<50%)"
    
    return {
        "id": dim_data.get("id", ""),
        "construct": dim_data.get("construct", ""),
        "description_paragraphs": dim_data["description"],
        "sub_dim_interpretation": dim_data.get("sub_dim_interpretation", {}),
        "band_narrative": dim_data["band_narratives"].get(band_key, ""),
        "overuse_risks": dim_data.get("overuse_risks", ""),
        "cross_dynamics": dim_data.get("cross_dynamics", []),
        "coaching_prompts": dim_data.get("coaching_prompts", []),
        "apac_calibration": dim_data.get("apac_calibration", []),
        "score_pct": score_pct,
        "band": band_key.split(" ")[0]
    }
