"""
SPARK Dimension Content Library — Gold Standard Narratives
SPARK: Organisational Diagnostic Assessment
Business-oriented, APAC-calibrated, Hogan/DISC-quality depth.
"""

SPARK_DIMENSIONS = {
    "INDIVIDUAL AI ADOPTION READINESS (IAAR)": {
    "id": "D1",
    "construct": "AI Leadership Readiness & Enterprise Governance - INDIVIDUAL AI ADOPTION READINESS (IAAR)",
    "description": [
        "This dimension measures the extent to which a leader has restructured their professional workflow through sustained, systematic integration of AI tools—not sporadic experimentation or delegated usage. It captures the leader's personal adoption depth, frequency, and strategic alignment of AI across decision-making, communication, and operational tasks, serving as a leading indicator of organisational AI culture. When a leader fails to embed AI into their own routines, it signals to teams that AI is optional rather than foundational, stalling enterprise-wide adoption and governance maturity. IAAR is distinct from technical proficiency; it assesses whether the leader treats AI as a core productivity lever and governance instrument, not a novelty.",
        "At an organisational level, IAAR directly correlates with the speed and quality of AI governance framework implementation. Leaders who personally adopt AI systematically are more likely to mandate data hygiene standards, invest in capability exposure pipelines, and enforce ethical use policies—because they understand the operational realities and risks firsthand. Conversely, low IAAR in senior leadership creates a governance vacuum: AI adoption becomes fragmented, shadow IT proliferates, and risk management remains reactive. This dimension thus functions as a diagnostic for whether the organisation's AI strategy is performative or embedded in daily operations.",
        "In APAC business contexts, IAAR is particularly critical due to the region's rapid digitalisation, hierarchical decision-making structures, and varying regulatory landscapes. Leaders in markets like Singapore, Japan, and South Korea face pressure to adopt AI for competitive positioning, yet cultural deference to seniority can mask low personal adoption—subordinates may not challenge a leader's lack of AI integration. Cross-border operations in China, India, and Southeast Asia further complicate IAAR, as leaders must navigate fragmented data ecosystems and differing AI literacy levels across teams. A leader's personal adoption readiness directly impacts their ability to govern AI across diverse APAC markets, where trust in AI systems is often lower and regulatory compliance demands are escalating."
    ],
    "sub_dim_interpretation": {
        "Workflow Integration Depth": "High scores indicate the leader has embedded AI into at least three core workflows (e.g., data analysis, meeting synthesis, strategic planning) with measurable productivity gains; low scores reflect isolated or inconsistent use, often limited to basic tasks like email drafting.",
        "Strategic Alignment of AI Use": "High scores show the leader applies AI to high-value decisions, such as market forecasting or risk assessment, aligning with organisational goals; low scores indicate AI is used for low-stakes tasks, missing strategic leverage.",
        "Frequency and Consistency of Adoption": "High scores reflect daily, habitual AI use across multiple contexts, with minimal friction; low scores reveal sporadic engagement, often triggered by external pressure or specific projects, not sustained practice.",
        "Delegation vs. Personal Engagement": "High scores mean the leader personally interacts with AI tools, understanding their outputs and limitations; low scores indicate heavy reliance on subordinates to operate AI, creating a knowledge gap and governance blind spots.",
        "Adaptability to New AI Tools": "High scores demonstrate proactive exploration and rapid integration of emerging AI capabilities; low scores show resistance or delayed adoption, often due to comfort with legacy methods or fear of obsolescence.",
        "Risk-Aware Adoption Behaviour": "High scores reflect conscious consideration of data privacy, bias, and compliance in AI use; low scores indicate reckless or uninformed adoption, increasing organisational exposure to regulatory and reputational risks."
    },
    "band_narratives": {
        "Strong (≥70%)": "Leaders at this level have restructured their workflows to leverage AI for strategic decision-making, operational efficiency, and team coordination, with measurable outcomes such as 20-30% time savings on analytical tasks. They model AI governance by personally adhering to data protocols and ethical guidelines, creating a culture where AI adoption is expected and governed. The risk at this level is over-reliance: leaders may assume AI outputs are infallible, reducing critical oversight and introducing systemic bias into decisions. Organisational impact includes faster innovation cycles and stronger governance, but requires counterbalancing with human judgment checks.",
        "Developing (50-69%)": "These leaders use AI in specific, high-impact areas but have not achieved full workflow integration, often defaulting to manual processes under pressure or for complex tasks. Adoption breaks down when AI requires cross-functional data sharing or when tools lack localisation for APAC markets, leading to inconsistent team adoption. The development priority is to identify two workflows where AI can replace repetitive tasks, freeing capacity for strategic oversight, while building a personal habit of daily AI engagement. Without this shift, the leader risks being a bottleneck in the organisation's AI transformation, as their team mirrors their selective adoption.",
        "Gap (<50%)": "Leaders in this band demonstrate minimal or no systematic AI integration, often delegating AI use entirely or avoiding it due to perceived complexity or irrelevance. This manifests in business contexts as delayed decision-making, reliance on outdated data, and a team culture where AI is seen as optional or threatening. The organisational cost is significant: the leader cannot govern AI risks they do not understand, leaving the enterprise exposed to compliance failures and competitive erosion. Change requires a structured exposure programme, starting with low-risk, high-return AI applications in their direct workflow, coupled with accountability metrics for adoption."
    },
    "overuse_risks": "When IAAR is over-applied without governance maturity, leaders become hyper-reliant on AI for all decisions, including those requiring nuanced human judgment, such as talent assessments or ethical trade-offs. This dysfunction manifests as algorithmic complacency, where leaders accept AI recommendations uncritically, reducing organisational resilience and innovation. The organisational cost includes erosion of critical thinking skills, increased bias in decision-making, and potential regulatory penalties in APAC markets with strict AI governance laws (e.g., Singapore's Model AI Governance Framework). Overuse also risks alienating teams who perceive AI as replacing human expertise, undermining trust and collaboration.",
    "cross_dynamics": [
        {"dim": "CAPABILITY EXPOSURE ASSESSMENT (CEA)", "interaction": "High IAAR amplifies CEA by enabling leaders to personally identify capability gaps in their teams through direct AI use, accelerating targeted upskilling. Conversely, low IAAR blinds leaders to CEA needs, as they cannot assess AI literacy they lack themselves, creating a skills pipeline bottleneck.", "risk": "high"},
        {"dim": "ORGANISATIONAL PREPAREDNESS (OP)", "interaction": "Strong IAAR drives OP by ensuring leaders champion data infrastructure investments and governance frameworks from an informed position, aligning personal adoption with enterprise strategy. Tension arises when IAAR outpaces OP, leading to frustration as leaders encounter organisational barriers like poor data quality or legacy systems that hinder scaling.", "risk": "medium"}
    ],
    "coaching_prompts": [
        "Describe a specific decision you made last week where AI influenced the outcome—what was the tool, how did you validate its output, and what would you have done differently without it?",
        "Identify one workflow you currently manage manually that could be restructured with AI; what is the primary barrier—technical, cultural, or personal—preventing that change?",
        "How do you ensure your AI use aligns with your organisation's data governance policies, and what gaps have you observed in your own compliance?",
        "Think of a team member who has adopted AI more effectively than you; what specific practices or tools have they integrated that you have not, and why?",
        "If your organisation mandated AI use for all strategic reports starting next quarter, what would be the first three changes you would make to your own workflow?",
        "How do you balance AI-driven efficiency with the need for human judgment in high-stakes decisions, and where have you seen this balance fail in your organisation?"
    ],
    "apac_calibration": [
        "In Japan and South Korea, high IAAR may be masked by cultural norms of humility, where leaders underreport AI use; calibration requires observing actual workflow changes rather than self-assessments, and focusing on team adoption patterns as a proxy.",
        "In Southeast Asian markets like Indonesia and Vietnam, IAAR is often constrained by infrastructure gaps (e.g., unreliable internet, limited localised AI tools); leaders must be assessed on adaptive adoption, such as using offline AI solutions or mobile-first tools, not just sophisticated platforms.",
        "In China, IAAR is heavily influenced by state-driven AI ecosystems and regulatory controls; leaders may demonstrate high adoption but with limited risk awareness due to centralised governance, requiring calibration for compliance consciousness rather than usage volume.",
        "Across APAC, cross-border leaders often exhibit fragmented IAAR, with strong adoption in headquarters but weak integration in regional offices; calibration must assess consistency across markets, as this directly impacts governance uniformity and risk exposure."
    ]
},

    "CAPABILITY EXPOSURE ASSESSMENT (CEA)": {
    "id": "D2",
    "construct": "AI Leadership Readiness & Enterprise Governance - CAPABILITY EXPOSURE ASSESSMENT (CEA)",
    "description": [
        "This dimension measures a leader's capacity to systematically identify which professional capabilities within their organisation are vulnerable to AI-driven obsolescence and which are poised to increase in strategic value. It moves beyond personal career anxiety to assess whether the leader can conduct a rigorous, role-level audit of task automation potential, skill complementarity with AI, and emerging competency demands across the enterprise. This matters because workforce planning decisions based on intuition rather than structured exposure analysis will result in misallocated reskilling budgets, retention failures in critical roles, and competitive blind spots as AI reshapes industry cost structures. The dimension is a direct predictor of whether the organisation can execute a proactive talent transformation rather than react to capability shocks.",
        "At the organisational level, CEA reveals whether the leader can translate capability exposure insights into strategic workforce architecture decisions, such as restructuring team compositions, redesigning career pathways, and recalibrating hiring criteria for AI-augmented workflows. It assesses the leader's ability to commission and interpret capability heatmaps that map automation probability against business criticality, enabling targeted investment in upskilling for high-value, low-automation roles while planning redeployment or redundancy for highly automatable functions. A leader strong in CEA does not merely list at-risk roles but quantifies the financial impact of capability erosion, models future-state skill inventories, and aligns these with the organisation's AI adoption roadmap. The organisational cost of weak CEA is a workforce strategy that is either overly defensive, hoarding redundant talent, or recklessly aggressive, cutting capabilities that could have been augmented for higher productivity.",
        "In APAC business contexts, CEA is particularly critical due to the region's heavy reliance on cost-arbitrage labour models, where large pools of transactional and process-driven roles in shared services, manufacturing, and back-office operations face acute AI exposure. Leaders in markets like Singapore, Malaysia, and India must navigate the tension between maintaining short-term labour cost advantages and investing in higher-value cognitive roles that AI augments, a calculus complicated by varying labour market rigidities and social safety nets across jurisdictions. Furthermore, the rapid digitalisation of Asian economies, combined with demographic pressures in markets like Japan and South Korea, means that capability exposure assessments must account for cultural resistance to role redefinition and the need for government-linked retraining ecosystems. A leader who fails to calibrate CEA for APAC-specific workforce structures—such as the prevalence of contract labour in Southeast Asia or the seniority-based promotion systems in Northeast Asia—will produce exposure analyses that are analytically sound but organisationally unactionable."
    ],
    "sub_dim_interpretation": {
        "Task Automation Vulnerability Analysis": "High scores indicate the leader can granularly decompose roles into constituent tasks and accurately assess automation probability using industry benchmarks and AI capability curves. Low scores reflect a tendency to rely on broad job titles or anecdotal evidence, leading to either overestimation of risk in roles with high tacit knowledge or underestimation in process-heavy functions.",
        "Skill Complementarity Identification": "High scores demonstrate the ability to pinpoint which human capabilities—such as complex negotiation, cross-domain creativity, or ethical judgment—are amplified by AI tools, enabling strategic role redesign. Low scores result in a binary view of AI as a replacement threat, missing opportunities to create hybrid roles that combine human judgment with machine scale.",
        "Strategic Workforce Planning Integration": "High scores reflect the capacity to embed exposure insights into multi-year workforce plans, including hiring targets, learning budgets, and succession pipelines calibrated for AI-augmented futures. Low scores indicate a siloed analysis that fails to influence resourcing decisions, leaving the organisation with a capability strategy disconnected from AI investment.",
        "Critical Role Retention & Redeployment": "High scores show the leader can identify roles where human expertise becomes more scarce and valuable post-AI, and can design retention incentives and redeployment pathways for impacted talent. Low scores manifest as either blanket retention of at-risk roles or abrupt layoffs that destroy institutional knowledge and morale.",
        "Financial Impact Modelling of Capability Shifts": "High scores enable the leader to quantify the cost-benefit of reskilling versus replacing, including productivity gains from AI augmentation and severance costs from automation. Low scores lead to workforce decisions based on headcount reduction targets alone, ignoring the long-term value of upskilled talent in AI-enabled workflows.",
        "Cross-Functional Capability Audit Governance": "High scores establish a repeatable process for periodic capability audits across business units, with clear ownership and escalation to the board. Low scores result in ad-hoc, one-off analyses that quickly become obsolete as AI capabilities evolve, leaving the organisation perpetually reactive."
    },
    "band_narratives": {
        "Strong (≥70%)": "Leaders at this level systematically audit their organisation's capability exposure using data-driven models that map task automation probability against business criticality, producing actionable heatmaps for each function. They actively redesign roles to leverage AI augmentation, shifting talent from transactional tasks to higher-value judgment and relationship work, and have quantifiable metrics for reskilling ROI. The organisational impact is a workforce that is leaner in automatable areas, denser in strategic capabilities, and more adaptable to AI-driven market shifts. The specific risk at this level is over-optimisation, where the leader may prematurely divest from capabilities that have latent value in unforeseen AI scenarios, or create a culture of constant role churn that undermines psychological safety.",
        "Developing (50-69%)": "Leaders in this band can identify broad categories of at-risk roles and articulate general trends in AI capability shifts, but their analysis lacks the granularity to inform specific workforce decisions. They may commission capability audits but struggle to translate findings into concrete reskilling programmes or hiring changes, often defaulting to generic training initiatives. This capability works well in stable, low-automation industries but breaks down in rapidly digitising sectors where precise exposure data is needed to avoid talent bottlenecks. The development priority is to build a structured framework for task-level decomposition and to establish a cross-functional governance process that ties exposure insights directly to budget allocation.",
        "Gap (<50%)": "Leaders at this level either dismiss AI capability exposure as a future concern or rely on superficial assessments that miss critical vulnerabilities in middle-management and knowledge-worker roles. They may actively resist workforce restructuring, viewing capability shifts as a threat to their own authority or team size, leading to hoarding of redundant talent. In business contexts, this manifests as surprise layoffs when automation hits, misaligned hiring that duplicates soon-to-be-automated functions, and a workforce that is both overstaffed in declining areas and understaffed in emerging ones. The fundamental change needed is a shift from defensive career management to strategic workforce stewardship, beginning with a mandatory, board-level capability exposure review."
    },
    "overuse_risks": "When over-applied, CEA can lead to a hyper-rational, reductionist view of human capital where every role is evaluated solely through the lens of automation potential, ignoring tacit knowledge, cultural fit, and long-term innovation capacity. Leaders may become overly aggressive in restructuring, creating a 'capability churn' that destroys institutional memory and erodes trust, as employees perceive themselves as fungible assets. The organisational cost is a brittle workforce optimised for current AI capabilities but unable to adapt to the next wave of AI-driven disruption, as the leader has stripped away the very human diversity and redundancy that enables resilience. This dysfunction is particularly acute in APAC markets with strong relational cultures, where rapid role redefinition without relational continuity can fracture team cohesion and increase voluntary turnover of high-potential talent.",
    "cross_dynamics": [
        {"dim": "INDIVIDUAL AI ADOPTION READINESS (IAAR)", "interaction": "CEA provides the strategic rationale for which AI tools to adopt by identifying capability gaps that AI can fill, while IAAR determines whether the leader can personally champion those tools. A leader strong in CEA but weak in IAAR may design an excellent workforce plan but fail to model AI adoption behaviours, creating a gap between strategy and execution. The synergy is that CEA identifies the 'what' and 'why' of AI adoption, while IAAR supplies the 'how' through personal credibility and hands-on experimentation.", "risk": "high"},
        {"dim": "ORGANISATIONAL PREPAREDNESS (OP)", "interaction": "CEA identifies the capability shifts needed, but OP determines whether the organisation has the data infrastructure, governance frameworks, and learning systems to execute the transition. A leader with strong CEA but weak OP will produce accurate exposure analyses that cannot be actioned due to inadequate data pipelines or rigid HR systems. The tension is that CEA may demand rapid workforce changes that OP cannot support, requiring the leader to sequence capability restructuring alongside infrastructure investment.", "risk": "high"}
    ],
    "coaching_prompts": [
        "Walk me through the last time you conducted a systematic audit of which roles in your organisation are most exposed to AI automation—what specific methodology did you use, and what was the single most surprising finding?",
        "If you had to redesign one of your current team's roles to be 30% more productive using AI within six months, which role would you choose and what specific tasks would you reassign to the AI versus the human?",
        "What is the financial cost to your organisation of retaining a capability that is 80% automatable versus reskilling that person into a role that is 20% automatable—and how did you calculate that?",
        "Think of a capability that was critical to your organisation three years ago but is now largely automated—what did you do with the people who held that capability, and what would you do differently with the benefit of hindsight?",
        "How do you currently differentiate between a role that is 'at risk' from AI and a role that is 'transformable' by AI, and what specific criteria do you use to make that distinction in your workforce planning?",
        "In your last board presentation on talent strategy, what specific data did you present about capability exposure to AI, and how did that data influence the allocation of the learning and development budget?"
    ],
    "apac_calibration": [
        "In markets like India and the Philippines, where large BPO and IT services sectors dominate, CEA must account for the high automation potential of voice-based and transactional roles, but also the opportunity to shift talent into AI training, prompt engineering, and process re-engineering roles that are emerging locally. A leader who applies a Western-centric exposure model may miss these adjacent capability pathways unique to APAC labour markets.",
        "In Japan and South Korea, where seniority-based promotion and lifetime employment norms persist, CEA must be calibrated for the cultural resistance to role redefinition, as mid-career managers may resist transitioning from supervisory to AI-augmented analytical roles. Leaders must design capability transition pathways that preserve status and face, such as creating new titles for AI-augmented roles rather than framing them as demotions.",
        "In Singapore and Hong Kong, where talent markets are highly fluid and cross-border, CEA must incorporate the risk of capability flight, where employees in exposed roles may leave for competitors rather than reskill internally. Leaders need to model the cost of replacing talent versus reskilling, factoring in the premium for AI-adjacent skills in these competitive markets.",
        "Across Southeast Asia, the prevalence of gig and contract labour means that CEA must differentiate between core and contingent workforce exposure, as automation of contract roles may be strategically desirable but socially sensitive. Leaders must navigate the tension between labour cost optimisation and the political risk of large-scale contract worker displacement in markets with weaker social safety nets."
    ]
},

    "ORGANISATIONAL PREPAREDNESS (OP)": {
    "id": "D3",
    "construct": "AI Leadership Readiness & Enterprise Governance - ORGANISATIONAL PREPAREDNESS (OP)",
    "description": [
        "Organisational Preparedness (OP) measures the maturity of an organisation's governance frameworks, data infrastructure, and capability development systems required to deploy AI at scale. This dimension moves beyond individual AI literacy to assess whether the enterprise has the structural foundations—such as AI ethics boards, data lineage protocols, and reskilling pipelines—to capture productivity gains while managing regulatory and reputational risk. In practice, OP determines whether AI initiatives remain isolated experiments or become embedded, value-generating capabilities across business units. Without strong OP, even the most AI-savvy leaders will fail to translate personal readiness into organisational transformation.",
        "At the organisational level, OP operates through three interconnected pillars: governance (e.g., decision rights for AI procurement, model risk management, and compliance with emerging regulations like Singapore's Model AI Governance Framework or the EU AI Act), data infrastructure (e.g., data quality standards, access controls, and interoperability across legacy systems), and capability development (e.g., structured upskilling for non-technical staff, AI ethics training for boards, and talent acquisition strategies for machine learning engineers). A high-OP organisation can rapidly assess AI use cases for feasibility, risk, and strategic alignment, then deploy resources accordingly. Conversely, low-OP manifests as fragmented AI pilots, shadow IT deployments of generative AI tools, and repeated failures to move from proof-of-concept to production. The diagnostic focus is on systemic readiness—not whether the CEO can prompt an LLM, but whether the organisation has the policies, data hygiene, and talent density to govern AI as a strategic asset.",
        "In APAC markets, OP is particularly critical due to the region's regulatory heterogeneity and rapid digitalisation. For example, Singapore's Infocomm Media Development Authority (IMDA) mandates AI governance for financial services, while Indonesia and Vietnam have less codified frameworks, creating compliance risks for cross-border deployments. Additionally, many APAC organisations operate with legacy data silos across subsidiaries in different jurisdictions, making data infrastructure a binding constraint. The dimension also captures cultural nuances: in hierarchical Asian business contexts, AI governance often requires board-level sponsorship to overcome middle-management resistance, whereas Western firms may delegate to CDO-level roles. OP thus serves as a litmus test for whether an organisation can navigate APAC's fragmented AI landscape without incurring regulatory penalties or strategic paralysis."
    ],
    "sub_dim_interpretation": {
        "AI Governance Maturity": "High scores indicate established AI ethics committees, clear model risk management protocols, and board-level oversight of AI strategy; low scores reflect ad-hoc decision-making, no formal AI procurement policies, and reliance on vendor claims without independent validation.",
        "Data Infrastructure Readiness": "High scores denote integrated data lakes with lineage tracking, role-based access controls, and automated data quality monitoring; low scores reveal fragmented data sources, manual ETL processes, and no systematic approach to data privacy compliance across jurisdictions.",
        "Capability Development Pipeline": "High scores show structured reskilling programs for non-technical staff, AI literacy for senior leadership, and partnerships with universities or bootcamps; low scores indicate one-off training sessions, no role-specific AI competencies, and reliance on external consultants without knowledge transfer.",
        "Risk & Compliance Integration": "High scores embed AI risk assessments into existing enterprise risk management (ERM) frameworks, with regular audits for bias, drift, and security; low scores treat AI risk as a standalone IT issue, with no cross-functional escalation paths or regulatory reporting mechanisms.",
        "Strategic Alignment & Investment": "High scores link AI investments to specific business outcomes (e.g., cost reduction, revenue growth) with clear ROI metrics and stage-gate funding; low scores fund AI projects based on hype or vendor pressure, with no portfolio-level prioritisation or post-implementation reviews."
    },
    "band_narratives": {
        "Strong (≥70%)": "Organisations in this band have operationalised AI governance as a core business function, with dedicated committees meeting quarterly to review model inventory, risk exposure, and strategic alignment. Data infrastructure is treated as a competitive asset, with automated pipelines ensuring data quality for both training and inference. The primary risk at this level is over-governance: excessive controls can slow innovation, create bureaucratic friction, and discourage experimentation. Leaders must guard against governance becoming a compliance checkbox rather than an enabler of responsible AI adoption.",
        "Developing (50-69%)": "These organisations have foundational governance elements—such as an AI ethics policy or a data catalog—but lack integration across functions. For example, a bank may have a model risk policy for credit scoring but no equivalent for generative AI chatbots used in customer service. The development priority is to move from siloed governance to an enterprise-wide AI operating model, including cross-functional risk committees and standardised data access protocols. Without this integration, AI initiatives will stall at the pilot stage due to inconsistent risk appetites across business units.",
        "Gap (<50%)": "Organisations in this band exhibit significant structural deficits: no formal AI governance, data stored in disconnected spreadsheets or legacy databases, and no systematic upskilling beyond a few data scientists. Business impact is severe: AI projects fail to scale, regulatory fines are likely (e.g., for non-compliance with data localisation laws in China or India), and the organisation is vulnerable to reputational damage from biased or insecure AI deployments. The immediate priority is to establish a minimum viable governance framework—starting with an AI use case inventory, a data quality audit, and board-level AI risk awareness training."
    },
    "overuse_risks": "When OP is over-applied, organisations develop governance sclerosis: excessive documentation, multi-layered approval processes, and risk aversion that kills innovation. This manifests as 'AI theatre'—teams spend more time filling compliance forms than building models, and promising use cases are abandoned due to bureaucratic friction. The organisational cost is strategic stagnation: competitors with leaner governance capture market share while the over-governed firm remains stuck in analysis paralysis. Leaders must balance governance rigour with agility, using tiered risk frameworks (e.g., low-risk internal tools vs. high-risk customer-facing systems) to avoid a one-size-fits-all approach."
    ,
    "cross_dynamics": [
        {
            "dim": "Individual AI Adoption Readiness (IAAR)",
            "interaction": "High IAAR without strong OP creates a 'wild west' scenario where individual leaders deploy AI tools without organisational oversight, leading to shadow IT, data leakage, and inconsistent risk management. Conversely, high OP with low IAAR results in well-governed but unused AI capabilities—frameworks exist but no one has the skills or motivation to apply them. The synergy occurs when IAAR drives bottom-up experimentation that is channelled through OP's governance guardrails, enabling rapid scaling of validated use cases.",
            "risk": "high"
        },
        {
            "dim": "Capability Exposure Assessment (CEA)",
            "interaction": "OP provides the structural context for CEA: an organisation with strong OP can systematically identify which roles are most exposed to AI disruption and proactively reskill or redeploy talent. Without OP, CEA becomes a theoretical exercise—leaders know which jobs are at risk but lack the governance mechanisms to execute transitions. The tension arises when CEA reveals high exposure but OP's capability pipeline is too slow to respond, creating workforce anxiety and attrition.",
            "risk": "medium"
        }
    ],
    "coaching_prompts": [
        "What specific governance mechanisms does your organisation have to approve or reject an AI use case, and who holds the final decision rights—the CTO, the risk committee, or the board?",
        "Describe the last time your organisation moved an AI project from proof-of-concept to production. What governance or infrastructure bottlenecks did you encounter, and how were they resolved?",
        "If a regulator asked for a complete inventory of all AI models in production across your organisation, including their training data sources and bias testing results, could you produce it within 30 days? Why or why not?",
        "What is the single most critical data quality issue in your organisation today that prevents an AI initiative from scaling, and what is the business cost of not fixing it?",
        "How does your organisation ensure that non-technical leaders—such as the head of marketing or supply chain—understand the risks and limitations of AI tools they are deploying?",
        "If you had to allocate a $10M AI budget across governance, data infrastructure, and capability development, what percentage would you assign to each, and why?"
    ],
    "apac_calibration": [
        "In Singapore and Hong Kong, regulatory pressure from MAS and HKMA drives higher OP scores in financial services, but this often creates a compliance-first culture that stifles innovation; leaders must calibrate governance to avoid over-indexing on risk at the expense of speed.",
        "In China, data localisation laws (e.g., the Personal Information Protection Law) and state-directed AI priorities mean OP must include government liaison capabilities and cross-border data transfer protocols, which are less relevant in Western contexts.",
        "In Southeast Asian markets like Indonesia and Vietnam, OP is often constrained by immature data infrastructure—many organisations lack basic data cataloging or quality monitoring—so the development priority is foundational data hygiene before advanced governance frameworks.",
        "In Japan and South Korea, hierarchical decision-making means OP requires explicit board-level sponsorship and consensus-building across silos; a top-down governance mandate is more effective than bottom-up experimentation, unlike in more individualistic Western cultures."
    ]
},

}



def get_dimension_content(dim_name: str, score_pct: float) -> dict:
    """Get gold-standard content for a dimension, with score-band selection."""
    dim_data = SPARK_DIMENSIONS.get(dim_name)
    if not dim_data:
        return None
    
    if score_pct >= 70:
        band_key = "Strong (>=70%)"
    elif score_pct >= 50:
        band_key = "Developing (50-69%)"
    else:
        band_key = "Gap (<50%)"
    
    return {
        "id": dim_data.get("id", ""),
        "construct": dim_data.get("construct", ""),
        "description_paragraphs": dim_data["description"],
        "sub_dim_interpretation": dim_data.get("sub_dim_interpretation", {}),
        "band_narrative": dim_data["band_narratives"].get(band_key, ""),
        "overuse_risks": dim_data.get("overuse_risks", ""),
        "cross_dynamics": dim_data.get("cross_dynamics", []),
        "coaching_prompts": dim_data.get("coaching_prompts", []),
        "apac_calibration": dim_data.get("apac_calibration", []),
        "score_pct": score_pct,
        "band": band_key.split(" ")[0]
    }
